# Generated by Django 5.2.17 on 2026-09-07 14:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GCOStaffProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee_number', models.CharField(blank=True, max_length=50, verbose_name='employee number')),
                ('designation', models.CharField(blank=True, help_text='Internal staff role title, e.g., Front Desk Coordinator.', max_length=100, verbose_name='designation')),
                ('user', models.OneToOneField(help_text='The linked User account.', on_delete=django.db.models.deletion.CASCADE, related_name='staff_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'GCO staff profile',
                'verbose_name_plural': 'GCO staff profiles',
            },
        ),
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student_number', models.CharField(blank=True, help_text='Unique student ID number.', max_length=50, null=True, unique=True, verbose_name='student number')),
                ('control_number', models.CharField(blank=True, help_text='Used for matching intake submissions before account registration.', max_length=50, null=True, unique=True, verbose_name='control number')),
                ('lifecycle_status', models.CharField(choices=[('ACTIVE', 'Active'), ('GRADUATING', 'Graduating'), ('GRADUATED', 'Graduated'), ('ALUMNI', 'Alumni'), ('TRANSFERRED', 'Transferred'), ('DROPPED_INACTIVE', 'Dropped / Inactive'), ('SUSPENDED_RESTRICTED', 'Suspended / Restricted'), ('ARCHIVED', 'Archived')], default='ACTIVE', help_text='Current enrollment or alumni status of the student.', max_length=30, verbose_name='lifecycle status')),
                ('campus', models.CharField(blank=True, help_text='UCN campus name, e.g. Main Campus.', max_length=100, verbose_name='campus')),
                ('college', models.CharField(blank=True, help_text='UCN college name, e.g. CCMS.', max_length=100, verbose_name='college')),
                ('department', models.CharField(blank=True, help_text='Academic department name.', max_length=100, verbose_name='department')),
                ('program', models.CharField(blank=True, help_text='Specific academic program/degree course.', max_length=100, verbose_name='program')),
                ('year_level', models.PositiveIntegerField(blank=True, help_text='Current academic year level.', null=True, verbose_name='year level')),
                ('user', models.OneToOneField(help_text='The linked User account.', on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'student profile',
                'verbose_name_plural': 'student profiles',
            },
        ),
        migrations.CreateModel(
            name='CounselorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_head_guidance', models.BooleanField(default=False, help_text='Designation flag indicating administrative authority over the office.', verbose_name='is head guidance')),
                ('license_number', models.CharField(blank=True, help_text='Professional guidance counselor license identification.', max_length=50, verbose_name='license number')),
                ('user', models.OneToOneField(help_text='The linked User account.', on_delete=django.db.models.deletion.CASCADE, related_name='counselor_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'counselor profile',
                'verbose_name_plural': 'counselor profiles',
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_head_guidance', True)), fields=('is_head_guidance',), name='profiles_one_active_head_guidance')],
            },
        ),
        migrations.CreateModel(
            name='StudentAcademicCohort',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('academic_year', models.CharField(db_index=True, max_length=50)),
                ('campus', models.CharField(blank=True, max_length=100)),
                ('college', models.CharField(blank=True, max_length=100)),
                ('college_code', models.CharField(blank=True, max_length=80)),
                ('department', models.CharField(blank=True, max_length=100)),
                ('program', models.CharField(blank=True, max_length=100)),
                ('program_code', models.CharField(blank=True, max_length=100)),
                ('year_level', models.PositiveIntegerField(blank=True, null=True)),
                ('enrollment_state', models.CharField(choices=[('ENROLLED', 'Enrolled'), ('EXCLUDED', 'Excluded from reporting cohort')], db_index=True, default='ENROLLED', max_length=20)),
                ('provenance', models.CharField(choices=[('IMPORT', 'Official import'), ('DEMO', 'Synthetic operating demo'), ('MANUAL', 'Authorized manual cohort capture')], default='MANUAL', max_length=20)),
                ('source_reference', models.CharField(blank=True, help_text='Non-PII source identifier, such as an import batch/row reference.', max_length=80)),
                ('student_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='academic_cohorts', to='profiles.studentprofile')),
            ],
            options={
                'verbose_name': 'student academic cohort',
                'verbose_name_plural': 'student academic cohorts',
                'indexes': [models.Index(fields=['academic_year', 'college', 'year_level'], name='profiles_st_academi_73e6a9_idx'), models.Index(fields=['academic_year', 'campus', 'department', 'program'], name='profiles_st_academi_f3537f_idx')],
                'constraints': [models.UniqueConstraint(fields=('student_profile', 'academic_year'), name='unique_student_academic_cohort')],
            },
        ),
    ]
