# Generated by Django 5.2.17 on 2026-09-07 14:06

import apps.security.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Referral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reference_code', models.CharField(editable=False, max_length=25, unique=True)),
                ('source_type', models.CharField(choices=[('FACULTY', 'Faculty'), ('ADVISER', 'Adviser'), ('INSTITUTIONAL_STAFF', 'Institutional Staff'), ('PARENT_GUARDIAN', 'Parent or Guardian'), ('GCO', 'Guidance Office'), ('OTHER', 'Other')], max_length=30)),
                ('referrer_display_snapshot', models.CharField(blank=True, max_length=255)),
                ('reason_text', models.TextField(blank=True)),
                ('reason_text_encrypted', apps.security.fields.EncryptedTextField(blank=True, default=None, null=True)),
                ('reason_category_code', models.CharField(blank=True, choices=[('UNCATEGORIZED', 'Uncategorized'), ('ACADEMIC', 'Academic'), ('ATTENDANCE', 'Attendance'), ('BEHAVIOR_OR_CONDUCT', 'Behavior or Conduct'), ('PERSONAL_OR_SOCIAL', 'Personal or Social'), ('FAMILY_OR_HOME', 'Family or Home'), ('FINANCIAL', 'Financial'), ('CAREER_OR_PLANNING', 'Career or Planning'), ('OTHER', 'Other')], default='UNCATEGORIZED', max_length=30)),
                ('occurred_at', models.DateTimeField(blank=True, null=True)),
                ('source_signed_on', models.DateField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('received_at', models.DateTimeField(blank=True, null=True)),
                ('course_snapshot', models.CharField(blank=True, max_length=100)),
                ('year_level_snapshot', models.CharField(blank=True, max_length=30)),
                ('block_snapshot', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('RECEIVED', 'Received'), ('UNDER_REVIEW', 'Under Review'), ('ACTION_REQUIRED', 'Action Required'), ('ESCALATED', 'Head Review'), ('CLOSED', 'Closed'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=30)),
                ('source_form_code', models.CharField(default='CNSC-OP-GTA-01F9', editable=False, max_length=50)),
                ('source_form_revision', models.PositiveIntegerField(default=1, editable=False)),
                ('source_form_family', models.CharField(default='referral_slip', editable=False, max_length=50)),
                ('internal_schema_version', models.PositiveIntegerField(default=1)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('close_reason_code', models.CharField(blank=True, choices=[('WORKFLOW_PROGRESSION', 'Workflow progression'), ('HEAD_REVIEW', 'Head review'), ('WORK_COMPLETED', 'Work completed'), ('DUPLICATE', 'Duplicate record'), ('INVALID_INTAKE', 'Invalid intake'), ('WRONG_STUDENT', 'Wrong student selected'), ('TRANSFER_REQUIRED', 'Transfer required'), ('OTHER_STRUCTURED', 'Other structured reason')], max_length=50)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('cancel_reason_code', models.CharField(blank=True, choices=[('WORKFLOW_PROGRESSION', 'Workflow progression'), ('HEAD_REVIEW', 'Head review'), ('WORK_COMPLETED', 'Work completed'), ('DUPLICATE', 'Duplicate record'), ('INVALID_INTAKE', 'Invalid intake'), ('WRONG_STUDENT', 'Wrong student selected'), ('TRANSFER_REQUIRED', 'Transfer required'), ('OTHER_STRUCTURED', 'Other structured reason')], max_length=50)),
                ('reopened_at', models.DateTimeField(blank=True, null=True)),
                ('reopen_reason_code', models.CharField(blank=True, choices=[('WORKFLOW_PROGRESSION', 'Workflow progression'), ('HEAD_REVIEW', 'Head review'), ('WORK_COMPLETED', 'Work completed'), ('DUPLICATE', 'Duplicate record'), ('INVALID_INTAKE', 'Invalid intake'), ('WRONG_STUDENT', 'Wrong student selected'), ('TRANSFER_REQUIRED', 'Transfer required'), ('OTHER_STRUCTURED', 'Other structured reason')], max_length=50)),
                ('creation_request_key', models.CharField(editable=False, max_length=100, unique=True)),
                ('assigned_counselor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_referrals', to=settings.AUTH_USER_MODEL)),
                ('cancelled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referrals_cancelled', to=settings.AUTH_USER_MODEL)),
                ('closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referrals_closed', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='referrals_created', to=settings.AUTH_USER_MODEL)),
                ('received_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referrals_received', to=settings.AUTH_USER_MODEL)),
                ('referred_by_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_referrals', to=settings.AUTH_USER_MODEL)),
                ('reopened_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referrals_reopened', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='referrals', to=settings.AUTH_USER_MODEL)),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referrals_submitted', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='referrals_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ReferralAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action_code', models.CharField(choices=[('PARENT_CONTACT_ATTEMPTED', 'Parent contact attempted'), ('PARENT_NOTIFICATION_RECORDED', 'Parent notification recorded'), ('CALL_SLIP_NEEDED', 'Call slip needed'), ('INTERVIEW_SCHEDULING_NEEDED', 'Interview scheduling needed'), ('MONITORING_RECORDED', 'Monitoring recorded'), ('HEAD_REVIEW_REQUESTED', 'Head review requested'), ('CLOSURE_RECOMMENDED', 'Closure recommended'), ('OTHER_OPERATIONAL_ACTION', 'Other operational action')], max_length=50)),
                ('outcome_code', models.CharField(blank=True, choices=[('ATTEMPTED', 'Attempted'), ('COMPLETED', 'Completed'), ('RECORDED', 'Recorded'), ('NO_RESPONSE', 'No response'), ('FOLLOW_UP_REQUIRED', 'Follow-up required'), ('NOT_APPLICABLE', 'Not applicable')], max_length=50)),
                ('remarks', models.TextField(blank=True)),
                ('remarks_encrypted', apps.security.fields.EncryptedTextField(blank=True, default=None, null=True)),
                ('performed_at', models.DateTimeField()),
                ('request_key', models.CharField(max_length=100)),
                ('performed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='referral_actions_performed', to=settings.AUTH_USER_MODEL)),
                ('referral', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='actions', to='referrals.referral')),
            ],
            options={
                'ordering': ['-performed_at'],
            },
        ),
        migrations.CreateModel(
            name='ReferralAssignmentHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reason_code', models.CharField(choices=[('WORKFLOW_PROGRESSION', 'Workflow progression'), ('HEAD_REVIEW', 'Head review'), ('WORK_COMPLETED', 'Work completed'), ('DUPLICATE', 'Duplicate record'), ('INVALID_INTAKE', 'Invalid intake'), ('WRONG_STUDENT', 'Wrong student selected'), ('TRANSFER_REQUIRED', 'Transfer required'), ('OTHER_STRUCTURED', 'Other structured reason')], max_length=50)),
                ('detail', models.TextField(blank=True)),
                ('detail_encrypted', apps.security.fields.EncryptedTextField(blank=True, default=None, null=True)),
                ('change_type', models.CharField(choices=[('INITIAL_ASSIGNMENT', 'Initial Assignment'), ('REASSIGNMENT', 'Reassignment')], max_length=30)),
                ('changed_at', models.DateTimeField()),
                ('changed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='referral_assignment_changes', to=settings.AUTH_USER_MODEL)),
                ('from_counselor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('referral', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignment_history', to='referrals.referral')),
                ('to_counselor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-changed_at'],
            },
        ),
        migrations.CreateModel(
            name='ReferralReassignmentRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('request_reason_code', models.CharField(choices=[('WORKFLOW_PROGRESSION', 'Workflow progression'), ('HEAD_REVIEW', 'Head review'), ('WORK_COMPLETED', 'Work completed'), ('DUPLICATE', 'Duplicate record'), ('INVALID_INTAKE', 'Invalid intake'), ('WRONG_STUDENT', 'Wrong student selected'), ('TRANSFER_REQUIRED', 'Transfer required'), ('OTHER_STRUCTURED', 'Other structured reason')], max_length=50)),
                ('request_detail', models.TextField(blank=True)),
                ('request_detail_encrypted', apps.security.fields.EncryptedTextField(blank=True, default=None, null=True)),
                ('request_key', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('DECLINED', 'Declined'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('decision_code', models.CharField(blank=True, choices=[('WORKFLOW_PROGRESSION', 'Workflow progression'), ('HEAD_REVIEW', 'Head review'), ('WORK_COMPLETED', 'Work completed'), ('DUPLICATE', 'Duplicate record'), ('INVALID_INTAKE', 'Invalid intake'), ('WRONG_STUDENT', 'Wrong student selected'), ('TRANSFER_REQUIRED', 'Transfer required'), ('OTHER_STRUCTURED', 'Other structured reason')], max_length=50)),
                ('decision_detail', models.TextField(blank=True)),
                ('decision_detail_encrypted', apps.security.fields.EncryptedTextField(blank=True, default=None, null=True)),
                ('current_counselor_snapshot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('decider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referral_reassignment_decisions', to=settings.AUTH_USER_MODEL)),
                ('proposed_counselor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proposed_referral_reassignments', to=settings.AUTH_USER_MODEL)),
                ('referral', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reassignment_requests', to='referrals.referral')),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='referral_reassignment_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReferralStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('from_status', models.CharField(blank=True, max_length=30)),
                ('to_status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('RECEIVED', 'Received'), ('UNDER_REVIEW', 'Under Review'), ('ACTION_REQUIRED', 'Action Required'), ('ESCALATED', 'Head Review'), ('CLOSED', 'Closed'), ('CANCELLED', 'Cancelled')], max_length=30)),
                ('reason_code', models.CharField(blank=True, choices=[('WORKFLOW_PROGRESSION', 'Workflow progression'), ('HEAD_REVIEW', 'Head review'), ('WORK_COMPLETED', 'Work completed'), ('DUPLICATE', 'Duplicate record'), ('INVALID_INTAKE', 'Invalid intake'), ('WRONG_STUDENT', 'Wrong student selected'), ('TRANSFER_REQUIRED', 'Transfer required'), ('OTHER_STRUCTURED', 'Other structured reason')], max_length=50)),
                ('reason_detail', models.TextField(blank=True)),
                ('reason_detail_encrypted', apps.security.fields.EncryptedTextField(blank=True, default=None, null=True)),
                ('transitioned_at', models.DateTimeField()),
                ('request_key', models.CharField(blank=True, max_length=100)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='referral_status_changes', to=settings.AUTH_USER_MODEL)),
                ('referral', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='status_history', to='referrals.referral')),
            ],
            options={
                'ordering': ['-transitioned_at'],
            },
        ),
        migrations.AddIndex(
            model_name='referral',
            index=models.Index(fields=['status', 'updated_at'], name='referrals_r_status_229e5b_idx'),
        ),
        migrations.AddIndex(
            model_name='referral',
            index=models.Index(fields=['assigned_counselor', 'status'], name='referrals_r_assigne_b1f007_idx'),
        ),
        migrations.AddIndex(
            model_name='referral',
            index=models.Index(fields=['student', 'status'], name='referrals_r_student_49a1b8_idx'),
        ),
        migrations.AddIndex(
            model_name='referral',
            index=models.Index(fields=['received_at'], name='referrals_r_receive_e9aa92_idx'),
        ),
        migrations.AddConstraint(
            model_name='referral',
            constraint=models.CheckConstraint(condition=models.Q(('source_type__in', ['FACULTY', 'ADVISER', 'INSTITUTIONAL_STAFF', 'PARENT_GUARDIAN', 'GCO', 'OTHER'])), name='referral_source_type_known'),
        ),
        migrations.AddConstraint(
            model_name='referral',
            constraint=models.CheckConstraint(condition=models.Q(('reason_category_code__in', ['', 'UNCATEGORIZED', 'ACADEMIC', 'ATTENDANCE', 'BEHAVIOR_OR_CONDUCT', 'PERSONAL_OR_SOCIAL', 'FAMILY_OR_HOME', 'FINANCIAL', 'CAREER_OR_PLANNING', 'OTHER'])), name='referral_reason_category_known'),
        ),
        migrations.AddConstraint(
            model_name='referral',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['DRAFT', 'SUBMITTED', 'RECEIVED', 'UNDER_REVIEW', 'ACTION_REQUIRED', 'ESCALATED', 'CLOSED', 'CANCELLED'])), name='referral_status_known'),
        ),
        migrations.AddConstraint(
            model_name='referral',
            constraint=models.CheckConstraint(condition=models.Q(('close_reason_code__in', ['', 'WORKFLOW_PROGRESSION', 'HEAD_REVIEW', 'WORK_COMPLETED', 'DUPLICATE', 'INVALID_INTAKE', 'WRONG_STUDENT', 'TRANSFER_REQUIRED', 'OTHER_STRUCTURED'])), name='referral_close_reason_known'),
        ),
        migrations.AddConstraint(
            model_name='referral',
            constraint=models.CheckConstraint(condition=models.Q(('cancel_reason_code__in', ['', 'WORKFLOW_PROGRESSION', 'HEAD_REVIEW', 'WORK_COMPLETED', 'DUPLICATE', 'INVALID_INTAKE', 'WRONG_STUDENT', 'TRANSFER_REQUIRED', 'OTHER_STRUCTURED'])), name='referral_cancel_reason_known'),
        ),
        migrations.AddConstraint(
            model_name='referral',
            constraint=models.CheckConstraint(condition=models.Q(('reopen_reason_code__in', ['', 'WORKFLOW_PROGRESSION', 'HEAD_REVIEW', 'WORK_COMPLETED', 'DUPLICATE', 'INVALID_INTAKE', 'WRONG_STUDENT', 'TRANSFER_REQUIRED', 'OTHER_STRUCTURED'])), name='referral_reopen_reason_known'),
        ),
        migrations.AddConstraint(
            model_name='referralaction',
            constraint=models.UniqueConstraint(fields=('referral', 'request_key'), name='uniq_referral_action_request'),
        ),
        migrations.AddConstraint(
            model_name='referralaction',
            constraint=models.CheckConstraint(condition=models.Q(('action_code__in', ['PARENT_CONTACT_ATTEMPTED', 'PARENT_NOTIFICATION_RECORDED', 'CALL_SLIP_NEEDED', 'INTERVIEW_SCHEDULING_NEEDED', 'MONITORING_RECORDED', 'HEAD_REVIEW_REQUESTED', 'CLOSURE_RECOMMENDED', 'OTHER_OPERATIONAL_ACTION'])), name='referral_action_code_known'),
        ),
        migrations.AddConstraint(
            model_name='referralaction',
            constraint=models.CheckConstraint(condition=models.Q(('outcome_code__in', ['', 'ATTEMPTED', 'COMPLETED', 'RECORDED', 'NO_RESPONSE', 'FOLLOW_UP_REQUIRED', 'NOT_APPLICABLE'])), name='referral_action_outcome_known'),
        ),
        migrations.AddConstraint(
            model_name='referralassignmenthistory',
            constraint=models.CheckConstraint(condition=models.Q(('reason_code__in', ['WORKFLOW_PROGRESSION', 'HEAD_REVIEW', 'WORK_COMPLETED', 'DUPLICATE', 'INVALID_INTAKE', 'WRONG_STUDENT', 'TRANSFER_REQUIRED', 'OTHER_STRUCTURED'])), name='referral_assignment_reason_known'),
        ),
        migrations.AddConstraint(
            model_name='referralassignmenthistory',
            constraint=models.CheckConstraint(condition=models.Q(('change_type__in', ['INITIAL_ASSIGNMENT', 'REASSIGNMENT'])), name='referral_assignment_change_type_known'),
        ),
        migrations.AddConstraint(
            model_name='referralreassignmentrequest',
            constraint=models.UniqueConstraint(fields=('referral', 'request_key'), name='uniq_referral_reassignment_request'),
        ),
        migrations.AddConstraint(
            model_name='referralreassignmentrequest',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'PENDING')), fields=('referral',), name='uniq_pending_referral_reassignment'),
        ),
        migrations.AddConstraint(
            model_name='referralreassignmentrequest',
            constraint=models.CheckConstraint(condition=models.Q(('request_reason_code__in', ['WORKFLOW_PROGRESSION', 'HEAD_REVIEW', 'WORK_COMPLETED', 'DUPLICATE', 'INVALID_INTAKE', 'WRONG_STUDENT', 'TRANSFER_REQUIRED', 'OTHER_STRUCTURED'])), name='referral_reassign_request_reason_known'),
        ),
        migrations.AddConstraint(
            model_name='referralreassignmentrequest',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['PENDING', 'APPROVED', 'DECLINED', 'CANCELLED'])), name='referral_reassign_status_known'),
        ),
        migrations.AddConstraint(
            model_name='referralreassignmentrequest',
            constraint=models.CheckConstraint(condition=models.Q(('decision_code__in', ['', 'WORKFLOW_PROGRESSION', 'HEAD_REVIEW', 'WORK_COMPLETED', 'DUPLICATE', 'INVALID_INTAKE', 'WRONG_STUDENT', 'TRANSFER_REQUIRED', 'OTHER_STRUCTURED'])), name='referral_reassign_decision_known'),
        ),
        migrations.AddConstraint(
            model_name='referralstatushistory',
            constraint=models.CheckConstraint(condition=models.Q(('from_status__in', ['', 'DRAFT', 'SUBMITTED', 'RECEIVED', 'UNDER_REVIEW', 'ACTION_REQUIRED', 'ESCALATED', 'CLOSED', 'CANCELLED'])), name='referral_history_from_status_known'),
        ),
        migrations.AddConstraint(
            model_name='referralstatushistory',
            constraint=models.CheckConstraint(condition=models.Q(('to_status__in', ['DRAFT', 'SUBMITTED', 'RECEIVED', 'UNDER_REVIEW', 'ACTION_REQUIRED', 'ESCALATED', 'CLOSED', 'CANCELLED'])), name='referral_history_to_status_known'),
        ),
        migrations.AddConstraint(
            model_name='referralstatushistory',
            constraint=models.CheckConstraint(condition=models.Q(('reason_code__in', ['', 'WORKFLOW_PROGRESSION', 'HEAD_REVIEW', 'WORK_COMPLETED', 'DUPLICATE', 'INVALID_INTAKE', 'WRONG_STUDENT', 'TRANSFER_REQUIRED', 'OTHER_STRUCTURED'])), name='referral_history_reason_known'),
        ),
    ]
