# Generated by Django 5.2.17 on 2026-09-07 14:06

import apps.security.fields
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('security', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RetentionEvaluation',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('environment', models.CharField(max_length=40)),
                ('evaluated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('record_category', models.SlugField(max_length=120)),
                ('candidate_count', models.PositiveIntegerField(default=0)),
                ('hold_count', models.PositiveIntegerField(default=0)),
                ('result_code', models.CharField(max_length=80)),
                ('safe_metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DataSubjectRequest',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reference_code', models.CharField(editable=False, max_length=40, unique=True)),
                ('subject_reference_hash', models.CharField(max_length=64, validators=[django.core.validators.RegexValidator('\\A[a-f0-9]{64}\\Z', 'This field must contain a 64-character HMAC reference.')])),
                ('request_type', models.CharField(choices=[('ACCESS', 'Access'), ('CORRECTION', 'Correction'), ('REVIEW', 'Review'), ('OTHER', 'Other approved request')], max_length=20)),
                ('target_category', models.SlugField(blank=True, max_length=120)),
                ('target_record_reference_hash', models.CharField(blank=True, max_length=64, validators=[django.core.validators.RegexValidator('\\A[a-f0-9]{64}\\Z', 'This field must contain a 64-character HMAC reference.')])),
                ('description_encrypted', apps.security.fields.EncryptedTextField(blank=True, max_plaintext_bytes=16384, null=True)),
                ('status', models.CharField(choices=[('SUBMITTED', 'Submitted'), ('IDENTITY_VERIFICATION_REQUIRED', 'Identity verification required'), ('UNDER_REVIEW', 'Under review'), ('MORE_INFORMATION_REQUIRED', 'More information required'), ('APPROVED', 'Approved'), ('PARTIALLY_FULFILLED', 'Partially fulfilled'), ('DENIED', 'Denied'), ('COMPLETED', 'Completed'), ('WITHDRAWN', 'Withdrawn'), ('CLOSED', 'Closed')], db_index=True, default='SUBMITTED', max_length=40)),
                ('submitted_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('identity_verified_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('decision_reason_code', models.CharField(blank=True, max_length=80)),
                ('decision_notes_encrypted', apps.security.fields.EncryptedTextField(blank=True, max_plaintext_bytes=16384, null=True)),
                ('fulfilled_at', models.DateTimeField(blank=True, null=True)),
                ('withdrawn_at', models.DateTimeField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('staff_assisted', models.BooleanField(default=False)),
                ('source_route', models.CharField(max_length=255)),
                ('request_correlation_id', models.CharField(blank=True, max_length=100)),
                ('assigned_reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_privacy_requests', to=settings.AUTH_USER_MODEL)),
                ('protected_fulfillment_file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='privacy_request_fulfillments', to='security.protectedfile')),
                ('requester', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='privacy_requests', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_privacy_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='DataSubjectRequestTransition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('from_status', models.CharField(blank=True, max_length=40)),
                ('to_status', models.CharField(choices=[('SUBMITTED', 'Submitted'), ('IDENTITY_VERIFICATION_REQUIRED', 'Identity verification required'), ('UNDER_REVIEW', 'Under review'), ('MORE_INFORMATION_REQUIRED', 'More information required'), ('APPROVED', 'Approved'), ('PARTIALLY_FULFILLED', 'Partially fulfilled'), ('DENIED', 'Denied'), ('COMPLETED', 'Completed'), ('WITHDRAWN', 'Withdrawn'), ('CLOSED', 'Closed')], max_length=40)),
                ('reason_code', models.CharField(max_length=80)),
                ('decision_evidence', models.JSONField(blank=True, default=dict)),
                ('occurred_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('actor_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transitions', to='privacy.datasubjectrequest')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PrivacyIncident',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('incident_code', models.CharField(editable=False, max_length=40, unique=True)),
                ('category', models.CharField(choices=[('UNAUTHORIZED_ACCESS', 'Unauthorized access'), ('TOKEN_OTP_ABUSE', 'Token or OTP abuse'), ('SENSITIVE_EXPORT', 'Sensitive export'), ('BACKUP_RESTORE_EXPOSURE', 'Backup or restore exposure'), ('ACCIDENTAL_DISCLOSURE', 'Accidental disclosure'), ('SUSPECTED_DATA_LOSS', 'Suspected data loss'), ('RETENTION_DISPOSAL_FAILURE', 'Retention or disposal failure')], max_length=40)),
                ('severity', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], max_length=20)),
                ('affected_workflow', models.CharField(blank=True, max_length=100)),
                ('affected_record_category', models.SlugField(blank=True, max_length=120)),
                ('discovered_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('INVESTIGATING', 'Investigating'), ('CONTAINED', 'Contained'), ('RESOLVED', 'Resolved'), ('DISMISSED', 'Dismissed')], db_index=True, default='OPEN', max_length=20)),
                ('containment_code', models.CharField(blank=True, max_length=80)),
                ('action_metadata', models.JSONField(blank=True, default=dict)),
                ('notification_decision', models.CharField(choices=[('PENDING', 'Pending assessment'), ('NOT_REQUIRED', 'Notification not required'), ('REQUIRED', 'Notification required'), ('COMPLETED', 'Notification completed')], default='PENDING', max_length=20)),
                ('related_event_ids', models.JSONField(blank=True, default=list)),
                ('safe_summary_code', models.CharField(blank=True, max_length=100)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_privacy_incidents', to=settings.AUTH_USER_MODEL)),
                ('reporter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reported_privacy_incidents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-discovered_at'],
            },
        ),
        migrations.CreateModel(
            name='PrivacyIncidentTransition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('from_status', models.CharField(blank=True, max_length=20)),
                ('to_status', models.CharField(choices=[('OPEN', 'Open'), ('INVESTIGATING', 'Investigating'), ('CONTAINED', 'Contained'), ('RESOLVED', 'Resolved'), ('DISMISSED', 'Dismissed')], max_length=20)),
                ('reason_code', models.CharField(max_length=80)),
                ('safe_evidence', models.JSONField(blank=True, default=dict)),
                ('occurred_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('actor_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('incident', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transitions', to='privacy.privacyincident')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PrivacyLegalHold',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('record_category', models.SlugField(max_length=120)),
                ('record_reference_hash', models.CharField(blank=True, max_length=64, validators=[django.core.validators.RegexValidator('\\A[a-f0-9]{64}\\Z', 'This field must contain a 64-character HMAC reference.')])),
                ('reason_code', models.CharField(max_length=80)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('RELEASED', 'Released')], default='ACTIVE', max_length=20)),
                ('placed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('released_at', models.DateTimeField(blank=True, null=True)),
                ('safe_reference', models.CharField(blank=True, max_length=255)),
                ('placed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='placed_privacy_holds', to=settings.AUTH_USER_MODEL)),
                ('released_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='released_privacy_holds', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PrivacyNoticeRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notice_identifier', models.SlugField(max_length=120)),
                ('version', models.CharField(max_length=40)),
                ('revision_hash', models.CharField(editable=False, max_length=64)),
                ('body_markdown', models.TextField()),
                ('source_reference', models.CharField(max_length=500)),
                ('effective_at', models.DateTimeField(blank=True, null=True)),
                ('locale', models.CharField(default='en', max_length=20)),
                ('purpose_workflow', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('PROPOSED', 'Proposed'), ('PUBLISHED', 'Published'), ('RETIRED', 'Retired'), ('BLOCKED', 'Blocked')], default='PROPOSED', max_length=20)),
                ('approval_state', models.CharField(choices=[('PENDING', 'Approval pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('approval_reference', models.CharField(blank=True, max_length=255)),
                ('source_verified_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_privacy_notice_revisions', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_privacy_notice_revisions', to=settings.AUTH_USER_MODEL)),
                ('supersedes', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='superseding_revisions', to='privacy.privacynoticerevision')),
            ],
            options={
                'ordering': ['notice_identifier', 'purpose_workflow', 'locale', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PrivacyAcceptanceEvent',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('purpose_workflow', models.CharField(max_length=100)),
                ('subject_reference_hash', models.CharField(max_length=64, validators=[django.core.validators.RegexValidator('\\A[a-f0-9]{64}\\Z', 'This field must contain a 64-character HMAC reference.')])),
                ('actor_type', models.CharField(choices=[('ANONYMOUS', 'Anonymous visitor'), ('STUDENT', 'Student'), ('COUNSELOR', 'Counselor'), ('GCO_STAFF', 'GCO Staff'), ('HEAD_GUIDANCE', 'Head Guidance'), ('IT_ADMIN', 'IT Admin'), ('VERIFIED_TOKEN', 'Verified token'), ('SYSTEM', 'System')], max_length=20)),
                ('decision', models.CharField(choices=[('ACCEPTED', 'Accepted'), ('DECLINED', 'Declined'), ('WITHDRAWN', 'Withdrawn')], max_length=20)),
                ('decided_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('source_route', models.CharField(max_length=255)),
                ('request_correlation_id', models.CharField(blank=True, max_length=100)),
                ('token_session_hash', models.CharField(blank=True, max_length=64, validators=[django.core.validators.RegexValidator('\\A[a-f0-9]{64}\\Z', 'This field must contain a 64-character HMAC reference.')])),
                ('subject_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='privacy_acceptance_events', to=settings.AUTH_USER_MODEL)),
                ('notice_revision', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='acceptance_events', to='privacy.privacynoticerevision')),
            ],
            options={
                'ordering': ['-decided_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PrivacyReviewerAuthorization',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('scopes', models.JSONField(default=list)),
                ('valid_from', models.DateTimeField(default=django.utils.timezone.now)),
                ('valid_until', models.DateTimeField(blank=True, null=True)),
                ('source_reference', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('EXPIRED', 'Expired'), ('REVOKED', 'Revoked')], default='ACTIVE', max_length=20)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('authorized_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issued_privacy_reviewer_authorizations', to=settings.AUTH_USER_MODEL)),
                ('authorized_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='privacy_reviewer_authorizations', to=settings.AUTH_USER_MODEL)),
                ('revoked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revoked_privacy_reviewer_authorizations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PrivacyWorkflowBinding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('purpose_workflow', models.SlugField(max_length=100, unique=True)),
                ('status', models.CharField(choices=[('PROPOSED', 'Proposed'), ('PUBLISHED', 'Published'), ('RETIRED', 'Retired'), ('BLOCKED', 'Blocked')], default='BLOCKED', max_length=20)),
                ('required', models.BooleanField(default=True)),
                ('source_reference', models.CharField(blank=True, max_length=500)),
                ('block_reason', models.CharField(blank=True, max_length=255)),
                ('notice_revision', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='workflow_bindings', to='privacy.privacynoticerevision')),
            ],
        ),
        migrations.CreateModel(
            name='RetentionRule',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('record_category', models.SlugField(max_length=120, unique=True)),
                ('retention_trigger', models.CharField(choices=[('ACTION_COMPLETED', 'After documented action'), ('LAST_ACTIVITY', 'After last activity'), ('SUBMISSION', 'After submission'), ('RECORD_CREATED', 'After record creation'), ('REVIEW_DATE', 'On review date'), ('OTHER', 'Other approved trigger')], max_length=30)),
                ('retention_period_days', models.PositiveIntegerField(blank=True, null=True)),
                ('review_due_at', models.DateTimeField(blank=True, null=True)),
                ('source_reference', models.CharField(max_length=500)),
                ('legal_basis', models.CharField(blank=True, max_length=255)),
                ('owner_role', models.CharField(max_length=80)),
                ('effective_at', models.DateTimeField(blank=True, null=True)),
                ('legal_hold_behavior', models.CharField(max_length=255)),
                ('disposal_method', models.CharField(max_length=255)),
                ('evidence_requirement', models.CharField(max_length=255)),
                ('exception_status', models.CharField(blank=True, max_length=80)),
                ('status', models.CharField(choices=[('PROPOSED', 'Proposed'), ('APPROVED', 'Approved'), ('ACTIVE', 'Active'), ('BLOCKED', 'Blocked'), ('RETIRED', 'Retired')], db_index=True, default='PROPOSED', max_length=20)),
                ('approval_reference', models.CharField(blank=True, max_length=255)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('approver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_retention_rules', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['record_category'],
            },
        ),
        migrations.CreateModel(
            name='RetentionRuleTransition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('from_status', models.CharField(blank=True, max_length=20)),
                ('to_status', models.CharField(choices=[('PROPOSED', 'Proposed'), ('APPROVED', 'Approved'), ('ACTIVE', 'Active'), ('BLOCKED', 'Blocked'), ('RETIRED', 'Retired')], max_length=20)),
                ('reason_code', models.CharField(max_length=80)),
                ('safe_evidence', models.JSONField(blank=True, default=dict)),
                ('effective_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('actor_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transitions', to='privacy.retentionrule')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddIndex(
            model_name='datasubjectrequest',
            index=models.Index(fields=['subject_reference_hash', 'status'], name='privacy_dat_subject_fe6f20_idx'),
        ),
        migrations.AddIndex(
            model_name='datasubjectrequest',
            index=models.Index(fields=['target_category', 'status'], name='privacy_dat_target__c3ff38_idx'),
        ),
        migrations.AddIndex(
            model_name='privacyincident',
            index=models.Index(fields=['category', 'status'], name='privacy_pri_categor_e5dd79_idx'),
        ),
        migrations.AddIndex(
            model_name='privacyincident',
            index=models.Index(fields=['severity', 'status'], name='privacy_pri_severit_7c8ce5_idx'),
        ),
        migrations.AddIndex(
            model_name='privacylegalhold',
            index=models.Index(fields=['record_category', 'status'], name='privacy_pri_record__0a1f6f_idx'),
        ),
        migrations.AddIndex(
            model_name='privacylegalhold',
            index=models.Index(fields=['record_reference_hash', 'status'], name='privacy_pri_record__407ad2_idx'),
        ),
        migrations.AddIndex(
            model_name='privacynoticerevision',
            index=models.Index(fields=['notice_identifier', 'purpose_workflow', 'locale', 'status'], name='privacy_pri_notice__e3ba8b_idx'),
        ),
        migrations.AddIndex(
            model_name='privacynoticerevision',
            index=models.Index(fields=['revision_hash'], name='privacy_pri_revisio_fbab0f_idx'),
        ),
        migrations.AddConstraint(
            model_name='privacynoticerevision',
            constraint=models.UniqueConstraint(fields=('notice_identifier', 'version', 'locale', 'purpose_workflow'), name='privacy_notice_revision_identity_unique'),
        ),
        migrations.AddIndex(
            model_name='privacyacceptanceevent',
            index=models.Index(fields=['subject_reference_hash', 'purpose_workflow'], name='privacy_pri_subject_dc3389_idx'),
        ),
        migrations.AddIndex(
            model_name='privacyacceptanceevent',
            index=models.Index(fields=['notice_revision', 'decision'], name='privacy_pri_notice__b81ba0_idx'),
        ),
        migrations.AddIndex(
            model_name='privacyreviewerauthorization',
            index=models.Index(fields=['authorized_user', 'status', 'valid_from', 'valid_until'], name='privacy_pri_authori_215ab7_idx'),
        ),
        migrations.AddIndex(
            model_name='privacyworkflowbinding',
            index=models.Index(fields=['purpose_workflow', 'status'], name='privacy_pri_purpose_4e1c57_idx'),
        ),
    ]
