# Generated by Django 5.2.17 on 2026-09-07 14:06

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PolicyRecord',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key', models.CharField(db_index=True, max_length=120)),
                ('schema_version', models.CharField(default='v1', max_length=32)),
                ('target_type', models.CharField(blank=True, default='', max_length=120)),
                ('target_reference', models.CharField(blank=True, default='', max_length=160)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING_APPROVAL', 'Pending approval'), ('ACTIVE', 'Active'), ('RETIRED', 'Retired')], db_index=True, default='DRAFT', max_length=24)),
                ('effectiveness', models.CharField(choices=[('EFFECTIVE', 'Effective'), ('DEPRECATED', 'Deprecated — retained for audit only')], db_index=True, default='EFFECTIVE', max_length=16)),
                ('configuration_json', models.JSONField(blank=True, default=dict)),
                ('effective_from', models.DateTimeField(blank=True, null=True)),
                ('effective_until', models.DateTimeField(blank=True, null=True)),
                ('source_reference', models.CharField(blank=True, max_length=255)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('activated_at', models.DateTimeField(blank=True, null=True)),
                ('retired_at', models.DateTimeField(blank=True, null=True)),
                ('rejected_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason_code', models.CharField(blank=True, max_length=80)),
                ('activated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activated_policy_records', to=settings.AUTH_USER_MODEL)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_policy_records', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_policy_records', to=settings.AUTH_USER_MODEL)),
                ('rejected_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rejected_policy_records', to=settings.AUTH_USER_MODEL)),
                ('retired_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='retired_policy_records', to=settings.AUTH_USER_MODEL)),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_policy_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='PolicyTransition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action', models.CharField(choices=[('DRAFT_CREATED', 'Draft created'), ('DRAFT_UPDATED', 'Draft updated'), ('SUBMITTED', 'Submitted for approval'), ('APPROVED', 'Approved'), ('ACTIVATED', 'Activated'), ('RETIRED', 'Retired'), ('REJECTED', 'Rejected')], max_length=30)),
                ('from_status', models.CharField(blank=True, max_length=24)),
                ('to_status', models.CharField(max_length=24)),
                ('reason_code', models.CharField(max_length=80)),
                ('safe_evidence', models.JSONField(blank=True, default=dict)),
                ('occurred_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('actor_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transitions', to='governance.policyrecord')),
            ],
            options={
                'ordering': ['-occurred_at', '-pk'],
            },
        ),
        migrations.CreateModel(
            name='DPOAppointment',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('valid_from', models.DateTimeField()),
                ('valid_until', models.DateTimeField(blank=True, null=True)),
                ('appointment_reference', models.CharField(max_length=255)),
                ('contact_email', models.EmailField(max_length=254)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('RETIRED', 'Retired')], db_index=True, default='ACTIVE', max_length=20)),
                ('appointed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('retired_at', models.DateTimeField(blank=True, null=True)),
                ('appointed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issued_dpo_appointments', to=settings.AUTH_USER_MODEL)),
                ('holder', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dpo_appointments', to=settings.AUTH_USER_MODEL)),
                ('retired_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='retired_dpo_appointments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['holder', 'status', 'valid_from', 'valid_until'], name='governance__holder__bef2d5_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'ACTIVE')), fields=('status',), name='governance_one_active_dpo_appointment')],
            },
        ),
        migrations.AddIndex(
            model_name='policyrecord',
            index=models.Index(fields=['key', 'status'], name='governance__key_840202_idx'),
        ),
        migrations.AddIndex(
            model_name='policyrecord',
            index=models.Index(fields=['key', 'target_type', 'target_reference', 'status'], name='governance__key_6a20fe_idx'),
        ),
        migrations.AddConstraint(
            model_name='policyrecord',
            constraint=models.UniqueConstraint(condition=models.Q(('effectiveness', 'EFFECTIVE'), ('status', 'ACTIVE')), fields=('key', 'target_type', 'target_reference'), name='governance_one_active_policy_target'),
        ),
    ]
