# Generated by Django 5.2.17 on 2026-09-07 14:06

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BackupJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('job_type', models.CharField(choices=[('database', 'Database'), ('media', 'Media'), ('protected_files', 'Protected Files'), ('full', 'Full'), ('config_snapshot', 'Config Snapshot'), ('verification', 'Verification')], default='full', max_length=50)),
                ('status', models.CharField(choices=[('requested', 'Requested'), ('queued', 'Queued'), ('running', 'Running'), ('succeeded', 'Succeeded'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('expired', 'Expired'), ('verified', 'Verified')], default='requested', max_length=50)),
                ('requested_at', models.DateTimeField()),
                ('queued_at', models.DateTimeField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('failed_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('safe_failure_reason_code', models.CharField(blank=True, max_length=100, null=True)),
                ('environment', models.CharField(max_length=100)),
                ('includes_database', models.BooleanField(default=False)),
                ('includes_media', models.BooleanField(default=False)),
                ('includes_protected_files', models.BooleanField(default=False)),
                ('includes_manifest', models.BooleanField(default=False)),
                ('includes_key_material', models.BooleanField(default=False)),
                ('storage_target_type', models.CharField(default='metadata_only', max_length=50)),
                ('manifest_hash_sha256', models.CharField(blank=True, max_length=64, null=True)),
                ('artifact_count', models.IntegerField(default=0)),
                ('total_size_bytes', models.BigIntegerField(default=0)),
                ('encrypted_at_rest', models.BooleanField(default=False)),
                ('retention_class', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('manual_hold', 'Manual Hold'), ('demo', 'Demo')], default='demo', max_length=50)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('metadata_json', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completed_backups', to=settings.AUTH_USER_MODEL)),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requested_backups', to=settings.AUTH_USER_MODEL)),
                ('started_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='started_backups', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Backup Job',
                'verbose_name_plural': 'Backup Jobs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BackupArtifact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('artifact_type', models.CharField(choices=[('database_dump', 'Database Dump'), ('media_manifest', 'Media Manifest'), ('media_archive', 'Media Archive'), ('protected_file_manifest', 'Protected File Manifest'), ('report_manifest', 'Report Manifest'), ('config_manifest', 'Config Manifest')], max_length=50)),
                ('storage_reference', models.CharField(max_length=255)),
                ('checksum_sha256', models.CharField(max_length=64)),
                ('size_bytes', models.BigIntegerField()),
                ('encryption_status', models.CharField(choices=[('not_applicable', 'Not Applicable'), ('pending', 'Pending'), ('encrypted', 'Encrypted'), ('verification_failed', 'Verification Failed')], default='pending', max_length=50)),
                ('key_version_reference', models.CharField(blank=True, max_length=100, null=True)),
                ('envelope_format', models.CharField(choices=[('fernet_v1', 'Legacy Fernet v1'), ('gpg_symmetric_v1', 'GPG symmetric v1')], default='fernet_v1', max_length=40)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('backup_job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artifacts', to='backups.backupjob')),
            ],
            options={
                'verbose_name': 'Backup Artifact',
                'verbose_name_plural': 'Backup Artifacts',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='BackupManifest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('manifest_schema_version', models.CharField(max_length=20)),
                ('manifest_hash_sha256', models.CharField(max_length=64)),
                ('payload_json', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('backup_job', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='manifest', to='backups.backupjob')),
            ],
            options={
                'verbose_name': 'Backup Manifest',
                'verbose_name_plural': 'Backup Manifests',
            },
        ),
        migrations.CreateModel(
            name='RestoreRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('authorization_recorded_at', models.DateTimeField(blank=True, null=True)),
                ('institutional_authorization_type', models.CharField(choices=[('head_guidance_recorded', 'Head Guidance Recorded'), ('institutional_memo', 'Institutional Memo'), ('incident_response', 'Incident Response'), ('other_safe_reference', 'Other Safe Reference')], max_length=50)),
                ('institutional_authorization_reference', models.CharField(max_length=255)),
                ('restore_scope', models.CharField(choices=[('database', 'Database'), ('media', 'Media'), ('protected_files', 'Protected Files'), ('full', 'Full'), ('metadata_validation', 'Metadata Validation')], default='full', max_length=50)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('requested', 'Requested'), ('authorization_pending', 'Authorization Pending'), ('authorized', 'Authorized'), ('archive_validated', 'Archive Validated'), ('restore_executed_offline', 'Restore Executed Offline'), ('floor_verified', 'Floor Verified'), ('postconditions_verified', 'Postconditions Verified'), ('ready_for_separate_go_no_go', 'Ready for Separate Go/No-Go'), ('dry_run_started', 'Dry Run Started'), ('dry_run_passed', 'Dry Run Passed'), ('dry_run_failed', 'Dry Run Failed'), ('restore_ready', 'Restore Ready'), ('restore_started', 'Restore Started'), ('restore_completed', 'Restore Completed'), ('restore_failed', 'Restore Failed'), ('cancelled', 'Cancelled')], default='draft', max_length=50)),
                ('safe_reason_code', models.CharField(max_length=100)),
                ('dry_run_result_code', models.CharField(blank=True, max_length=100, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('failed_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('metadata_json', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('authorization_recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='authorized_restores', to=settings.AUTH_USER_MODEL)),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requested_restores', to=settings.AUTH_USER_MODEL)),
                ('target_backup_job', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='restore_requests', to='backups.backupjob')),
                ('technical_operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='operated_restores', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Restore Request',
                'verbose_name_plural': 'Restore Requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RestoreChecklistItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('step_key', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('passed', 'Passed'), ('failed', 'Failed'), ('warning', 'Warning'), ('skipped', 'Skipped')], default='pending', max_length=50)),
                ('safe_message_code', models.CharField(blank=True, max_length=255, null=True)),
                ('recorded_at', models.DateTimeField(blank=True, null=True)),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_checklist_items', to=settings.AUTH_USER_MODEL)),
                ('restore_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklist_items', to='backups.restorerequest')),
            ],
            options={
                'verbose_name': 'Restore Checklist Item',
                'verbose_name_plural': 'Restore Checklist Items',
                'ordering': ['step_key'],
            },
        ),
    ]
