# Generated by Django 5.2.17 on 2026-09-07 14:06

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EncryptionKeyVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key_version', models.CharField(max_length=100, unique=True, verbose_name='key version')),
                ('key_purpose', models.CharField(choices=[('FIELD_ENCRYPTION', 'Field Encryption'), ('FILE_ENVELOPE_PLACEHOLDER', 'File Envelope Placeholder'), ('AUDIT_HASH_REFERENCE_PLACEHOLDER', 'Audit Hash Reference Placeholder')], max_length=50, verbose_name='key purpose')),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('DECRYPT_ONLY', 'Decrypt Only'), ('RETIRED', 'Retired'), ('DISABLED', 'Disabled')], default='ACTIVE', max_length=50, verbose_name='status')),
                ('source_alias', models.CharField(max_length=100, verbose_name='source alias')),
                ('secret_reference', models.CharField(max_length=255, verbose_name='secret reference')),
                ('algorithm', models.CharField(default='Fernet', max_length=50, verbose_name='algorithm')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('activated_at', models.DateTimeField(blank=True, null=True, verbose_name='activated at')),
                ('retired_at', models.DateTimeField(blank=True, null=True, verbose_name='retired at')),
                ('not_before', models.DateTimeField(blank=True, null=True, verbose_name='not before')),
                ('not_after', models.DateTimeField(blank=True, null=True, verbose_name='not after')),
                ('notes', models.TextField(blank=True, verbose_name='notes')),
                ('activated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activated_key_versions', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_key_versions', to=settings.AUTH_USER_MODEL)),
                ('retired_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='retired_key_versions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'encryption key version',
                'verbose_name_plural': 'encryption key versions',
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'ACTIVE')), fields=('key_purpose',), name='unique_active_key_per_purpose')],
            },
        ),
        migrations.CreateModel(
            name='ProtectedFile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('storage_backend_alias', models.CharField(max_length=100, verbose_name='storage backend alias')),
                ('bucket_name', models.CharField(max_length=100, verbose_name='bucket name')),
                ('object_key', models.CharField(max_length=255, unique=True, verbose_name='object key')),
                ('original_filename_display', models.CharField(blank=True, max_length=255, null=True, verbose_name='original filename display')),
                ('content_type', models.CharField(max_length=100, verbose_name='content type')),
                ('file_size_bytes', models.PositiveBigIntegerField(verbose_name='file size bytes')),
                ('checksum_sha256', models.CharField(max_length=64, verbose_name='checksum sha256')),
                ('classification', models.CharField(choices=[('PUBLIC', 'Public'), ('INTERNAL', 'Internal'), ('PROTECTED', 'Protected'), ('CONFIDENTIAL', 'Confidential'), ('OFFICIAL_RECORD', 'Official Record'), ('SECURITY_SENSITIVE', 'Security Sensitive')], max_length=50, verbose_name='classification')),
                ('purpose', models.CharField(choices=[('GENERATED_DOCUMENT', 'Generated Document'), ('COUNSELING_ATTACHMENT', 'Counseling Attachment'), ('ECOUNSELING_RECORDING', 'E-Counseling Recording'), ('ECOUNSELING_TRANSCRIPT', 'E-Counseling Transcript'), ('BACKUP_REFERENCE_PLACEHOLDER', 'Backup Reference Placeholder'), ('OFFICIAL_RECORD_RELEASE', 'Official Record Release'), ('ASSESSMENT_RESULT_FILE', 'Assessment Result File'), ('FORM_SOURCE_ATTACHMENT', 'Form Source Attachment'), ('OTHER', 'Other')], max_length=50, verbose_name='purpose')),
                ('owning_app_label', models.CharField(max_length=100, verbose_name='owning app label')),
                ('owning_model_name', models.CharField(max_length=100, verbose_name='owning model name')),
                ('owning_object_id', models.CharField(max_length=255, verbose_name='owning object id')),
                ('access_policy_key', models.CharField(max_length=100, verbose_name='access policy key')),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('ARCHIVED', 'Archived'), ('DELETED_MARKER', 'Deleted Marker'), ('QUARANTINED_PLACEHOLDER', 'Quarantined Placeholder'), ('SUPERSEDED', 'Superseded')], default='ACTIVE', max_length=50, verbose_name='status')),
                ('retention_hold', models.BooleanField(default=False, verbose_name='retention hold')),
                ('encryption_key_version', models.CharField(blank=True, max_length=100, null=True, verbose_name='encryption key version')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('archived_at', models.DateTimeField(blank=True, null=True, verbose_name='archived at')),
                ('deleted_marker_at', models.DateTimeField(blank=True, null=True, verbose_name='deleted marker at')),
                ('archived_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='archived_protected_files', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_protected_files', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'protected file',
                'verbose_name_plural': 'protected files',
                'indexes': [models.Index(fields=['owning_app_label', 'owning_model_name', 'owning_object_id'], name='security_pr_owning__ff1ed6_idx'), models.Index(fields=['status'], name='security_pr_status_95ae1d_idx'), models.Index(fields=['classification'], name='security_pr_classif_d9a7d9_idx'), models.Index(fields=['checksum_sha256'], name='security_pr_checksu_e2cb35_idx'), models.Index(fields=['created_at'], name='security_pr_created_de37b8_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('purpose', 'ECOUNSELING_RECORDING')), fields=('owning_app_label', 'owning_model_name', 'owning_object_id'), name='unique_recording_file_per_owner')],
            },
        ),
    ]
