# Generated by Django 5.2.17 on 2026-09-07 14:06

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documents', '0001_initial'),
        ('profiles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GoodMoralRequest',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reference_code', models.CharField(editable=False, help_text='Immutable unique lookup code (GMC-AYxxxx-xxxxxx).', max_length=30, unique=True, verbose_name='reference code')),
                ('request_type', models.CharField(choices=[('STUDENT', 'Student'), ('GRADUATE', 'Graduate')], max_length=20, verbose_name='request type')),
                ('applicant_display_name', models.CharField(max_length=255)),
                ('applicant_lifecycle_status', models.CharField(max_length=100)),
                ('applicant_campus', models.CharField(max_length=255)),
                ('applicant_college', models.CharField(max_length=255)),
                ('applicant_department', models.CharField(max_length=255)),
                ('applicant_program_degree', models.CharField(max_length=255)),
                ('applicant_year_level', models.CharField(blank=True, max_length=100)),
                ('applicant_major', models.CharField(blank=True, max_length=100)),
                ('applicant_semester', models.CharField(blank=True, max_length=100)),
                ('applicant_academic_year', models.CharField(max_length=100)),
                ('applicant_graduation_date', models.DateField(blank=True, null=True)),
                ('purpose_text', models.TextField(max_length=500, verbose_name='purpose text')),
                ('official_receipt_number', models.CharField(blank=True, max_length=100)),
                ('official_receipt_date', models.DateField(blank=True, null=True)),
                ('official_receipt_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('receipt_status', models.CharField(choices=[('PENDING', 'Pending'), ('ENCODED', 'Encoded'), ('VERIFIED', 'Verified'), ('REJECTED', 'Rejected')], default='PENDING', max_length=30)),
                ('receipt_encoded_at', models.DateTimeField(blank=True, null=True)),
                ('receipt_verified_at', models.DateTimeField(blank=True, null=True)),
                ('receipt_rejection_code', models.CharField(blank=True, max_length=50)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('ossd_verification_status', models.CharField(choices=[('PENDING', 'Pending'), ('VERIFIED', 'Verified'), ('NOT_REQUIRED', 'Not Required')], default='NOT_REQUIRED', max_length=30)),
                ('hold_rejection_reason_code', models.CharField(blank=True, max_length=50)),
                ('office_only_note', models.TextField(blank=True, help_text='Safe administrative metadata. Never store counseling notes or case details.', max_length=1000, verbose_name='office-only safe note')),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('approval_signatory_name', models.CharField(blank=True, max_length=255)),
                ('approval_signatory_title', models.CharField(blank=True, max_length=255)),
                ('generated_at', models.DateTimeField(blank=True, null=True)),
                ('generation_failure_code', models.CharField(blank=True, max_length=50)),
                ('printed_at', models.DateTimeField(blank=True, null=True)),
                ('dry_seal_status', models.CharField(choices=[('PENDING', 'Pending'), ('SEALED', 'External Registrar seal confirmed')], default='PENDING', max_length=30)),
                ('dry_seal_confirmation_method', models.CharField(blank=True, choices=[('STUDENT_ATTESTED', 'Student attested'), ('COUNSELOR_RECORDED', 'Counselor recorded'), ('GCO_STAFF_RECORDED', 'GCO Staff recorded')], default='', max_length=30)),
                ('dry_seal_confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('released_at', models.DateTimeField(blank=True, null=True)),
                ('voided_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('terminal_reason_code', models.CharField(blank=True, max_length=50)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('FOR_PAYMENT', 'For Payment'), ('PAYMENT_ENCODED', 'Payment Encoded'), ('FOR_RECORD_CHECKING', 'For Record Checking'), ('PENDING_MANUAL_OSSD_VERIFICATION', 'Pending Manual OSSD Verification'), ('ON_HOLD_FOR_REVIEW', 'On Hold for Review'), ('FOR_APPROVAL', 'For Approval'), ('APPROVED_FOR_GENERATION', 'Approved for Generation'), ('GENERATING', 'Generating'), ('GENERATED', 'Generated'), ('PRINTED', 'Printed'), ('RELEASED', 'Released'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled'), ('VOIDED', 'Voided'), ('ARCHIVED', 'Archived'), ('FAILED', 'Failed')], default='DRAFT', max_length=40)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_gmc_requests', to=settings.AUTH_USER_MODEL)),
                ('archived_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='archived_gmc_requests', to=settings.AUTH_USER_MODEL)),
                ('assigned_reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_review_gmc_requests', to=settings.AUTH_USER_MODEL)),
                ('cancelled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cancelled_gmc_requests', to=settings.AUTH_USER_MODEL)),
                ('dry_seal_confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_dry_seal_gmc_requests', to=settings.AUTH_USER_MODEL)),
                ('generated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_gmc_requests', to=settings.AUTH_USER_MODEL)),
                ('generated_document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='good_moral_requests', to='documents.generateddocument')),
                ('printed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='printed_gmc_requests', to=settings.AUTH_USER_MODEL)),
                ('receipt_encoded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='encoded_receipt_gmc_requests', to=settings.AUTH_USER_MODEL)),
                ('receipt_verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_receipt_gmc_requests', to=settings.AUTH_USER_MODEL)),
                ('released_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='released_gmc_requests', to=settings.AUTH_USER_MODEL)),
                ('requester_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='good_moral_requests', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_gmc_requests', to=settings.AUTH_USER_MODEL)),
                ('student_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='good_moral_requests', to='profiles.studentprofile')),
                ('voided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='voided_gmc_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'good moral request',
                'verbose_name_plural': 'good moral requests',
                'indexes': [models.Index(fields=['status'], name='good_moral__status_1c1fb0_idx'), models.Index(fields=['reference_code'], name='good_moral__referen_8715f4_idx'), models.Index(fields=['request_type'], name='good_moral__request_898b88_idx'), models.Index(fields=['requester_user'], name='good_moral__request_fce4ca_idx')],
            },
        ),
    ]
