# Generated by Django 5.2.17 on 2026-09-07 14:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account_security', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='accountrecoveryrequest',
            name='staff_actor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assisted_recovery_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='accountrecoveryrequest',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recovery_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='apitoken',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_tokens', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='securitythrottlestate',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='security_throttles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='trusteddevice',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trusted_devices', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='twostepchallenge',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='twostep_challenges', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='verifiedemailevidence',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verified_email_evidence', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='verifiedemailevidence',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_email_evidence_actions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='accountrecoveryrequest',
            index=models.Index(fields=['status', 'expires_at'], name='account_sec_status_8af237_idx'),
        ),
        migrations.AddIndex(
            model_name='apitoken',
            index=models.Index(fields=['user', 'status', 'expires_at'], name='account_sec_user_id_3c3a39_idx'),
        ),
        migrations.AddIndex(
            model_name='apitoken',
            index=models.Index(fields=['family_id', 'status'], name='account_sec_family__f98efb_idx'),
        ),
        migrations.AddIndex(
            model_name='apitoken',
            index=models.Index(fields=['token_type', 'status', 'expires_at'], name='account_sec_token_t_51a3bb_idx'),
        ),
        migrations.AddIndex(
            model_name='securitythrottlestate',
            index=models.Index(fields=['action_scope', 'status'], name='account_sec_action__8fb8c1_idx'),
        ),
        migrations.AddConstraint(
            model_name='securitythrottlestate',
            constraint=models.UniqueConstraint(fields=('action_scope', 'scope_key', 'status'), name='account_security_throttle_scope_unique'),
        ),
        migrations.AddIndex(
            model_name='trusteddevice',
            index=models.Index(fields=['status', 'trusted_until'], name='account_sec_status_51fb82_idx'),
        ),
        migrations.AddIndex(
            model_name='twostepchallenge',
            index=models.Index(fields=['status', 'expires_at'], name='account_sec_status_78e637_idx'),
        ),
        migrations.AddIndex(
            model_name='verifiedemailevidence',
            index=models.Index(fields=['user', 'status', 'email_hash'], name='account_sec_user_id_5a2a93_idx'),
        ),
        migrations.AddIndex(
            model_name='verifiedemailevidence',
            index=models.Index(fields=['status', 'email_hash'], name='account_sec_status_77ab0f_idx'),
        ),
    ]
