# Generated by Django 5.2.17 on 2026-09-07 14:06

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
        ('profiles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FormCollection',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('audience', models.CharField(choices=[('FRESHMEN', 'Freshmen'), ('GRADUATING', 'Graduating Students'), ('ALUMNI', 'Alumni'), ('STUDENTS', 'Students'), ('CUSTOM', 'Custom')], default='CUSTOM', max_length=50, verbose_name='audience')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('ACTIVE', 'Active / Open'), ('PAUSED', 'Paused'), ('CLOSED', 'Closed'), ('ARCHIVED', 'Archived')], default='DRAFT', max_length=30, verbose_name='status')),
                ('start_at', models.DateTimeField(verbose_name='start time')),
                ('end_at', models.DateTimeField(verbose_name='end time')),
                ('form_type', models.CharField(choices=[('individual_inventory', 'Individual Inventory'), ('exit_interview', 'Exit Interview'), ('graduate_tracer', 'Graduate Tracer Survey'), ('csm_feedback', 'Client Satisfaction Feedback'), ('alumni_access', 'Alumni Document Access'), ('custom_controlled', 'Custom Controlled Intake')], help_text='The classification/target key of the form.', max_length=50, verbose_name='form type')),
                ('launched_at', models.DateTimeField(blank=True, null=True, verbose_name='launched at')),
                ('closed_at', models.DateTimeField(blank=True, null=True, verbose_name='closed at')),
                ('metadata_json', models.JSONField(blank=True, default=dict, verbose_name='metadata')),
                ('closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='closed_collections', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_collections', to=settings.AUTH_USER_MODEL)),
                ('form_family', models.ForeignKey(blank=True, help_text='The target form family.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='collections', to='organizations.formfamily')),
                ('form_revision', models.ForeignKey(blank=True, help_text='The target form revision (required before launch).', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='collections', to='organizations.formrevision')),
                ('launched_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='launched_collections', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'form collection',
                'verbose_name_plural': 'form collections',
            },
        ),
        migrations.CreateModel(
            name='FormInvitation',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token_hash', models.CharField(db_index=True, max_length=255, unique=True, verbose_name='token hash')),
                ('selector', models.CharField(db_index=True, max_length=64, unique=True, verbose_name='selector')),
                ('target_form_key', models.CharField(max_length=50, verbose_name='target form key')),
                ('intended_recipient_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='intended recipient name')),
                ('intended_email_hash', models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='intended email hash')),
                ('control_number_hash', models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='control number hash')),
                ('student_number_hash', models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='student number hash')),
                ('expires_at', models.DateTimeField(verbose_name='expires at')),
                ('max_uses', models.PositiveIntegerField(default=1, verbose_name='max uses')),
                ('used_count', models.PositiveIntegerField(default=0, verbose_name='used count')),
                ('status', models.CharField(choices=[('ISSUED', 'Issued'), ('OPENED', 'Opened'), ('VERIFIED', 'Verified'), ('DRAFT_STARTED', 'Draft Started'), ('SUBMITTED', 'Submitted'), ('LINKED_TO_ACCOUNT', 'Linked to Account'), ('EXPIRED', 'Expired'), ('REVOKED', 'Revoked')], default='ISSUED', max_length=30, verbose_name='status')),
                ('verified_at', models.DateTimeField(blank=True, null=True, verbose_name='verified at')),
                ('first_opened_at', models.DateTimeField(blank=True, null=True, verbose_name='first opened at')),
                ('last_opened_at', models.DateTimeField(blank=True, null=True, verbose_name='last opened at')),
                ('submitted_at', models.DateTimeField(blank=True, null=True, verbose_name='submitted at')),
                ('revoked_at', models.DateTimeField(blank=True, null=True, verbose_name='revoked at')),
                ('revoke_reason', models.TextField(blank=True, null=True, verbose_name='revoke reason')),
                ('metadata_json', models.JSONField(blank=True, default=dict, verbose_name='metadata')),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='form_invitations', to='form_collection.formcollection')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_form_invitations', to=settings.AUTH_USER_MODEL)),
                ('linked_student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='form_invitations', to='profiles.studentprofile')),
                ('revoked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revoked_form_invitations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'form invitation',
                'verbose_name_plural': 'form invitations',
            },
        ),
        migrations.CreateModel(
            name='FormInvitationAttempt',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action_scope', models.CharField(default='VERIFY', max_length=50, verbose_name='action scope')),
                ('identifier_hash', models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='identifier hash')),
                ('ip_hash', models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='ip hash')),
                ('user_agent_hash', models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='user agent hash')),
                ('session_hash', models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='session hash')),
                ('status', models.CharField(choices=[('SUCCESS', 'Success'), ('FAILED', 'Failed'), ('RATE_LIMITED', 'Rate Limited'), ('EXPIRED', 'Expired'), ('REVOKED', 'Revoked')], max_length=30, verbose_name='status')),
                ('failure_reason', models.CharField(blank=True, choices=[('INVALID_TOKEN', 'Invalid Token'), ('INVALID_VERIFIER', 'Invalid Verifier'), ('EXPIRED', 'Expired'), ('REVOKED', 'Revoked'), ('MAX_USES', 'Max Uses Exceeded'), ('COLLECTION_INACTIVE', 'Collection Inactive')], max_length=100, null=True, verbose_name='failure reason')),
                ('metadata_json', models.JSONField(blank=True, default=dict, verbose_name='metadata')),
                ('collection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attempts', to='form_collection.formcollection')),
                ('form_invitation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attempts', to='form_collection.forminvitation')),
            ],
            options={
                'verbose_name': 'form invitation attempt',
                'verbose_name_plural': 'form invitation attempts',
            },
        ),
        migrations.CreateModel(
            name='InvitationBatch',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('invitation_batch_name', models.CharField(max_length=255, verbose_name='invitation batch name')),
                ('source_type', models.CharField(choices=[('MANUAL', 'Manual'), ('CSV_IMPORT', 'CSV Import'), ('SYSTEM_JOB', 'System Job')], default='MANUAL', max_length=50, verbose_name='source type')),
                ('total_requested', models.PositiveIntegerField(default=0, verbose_name='total requested')),
                ('total_issued', models.PositiveIntegerField(default=0, verbose_name='total issued')),
                ('total_failed', models.PositiveIntegerField(default=0, verbose_name='total failed')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('VALIDATING', 'Validating'), ('ISSUED', 'Issued'), ('PARTIALLY_ISSUED', 'Partially Issued'), ('FAILED', 'Failed'), ('REVOKED', 'Revoked'), ('ARCHIVED', 'Archived')], default='DRAFT', max_length=30, verbose_name='status')),
                ('issued_at', models.DateTimeField(blank=True, null=True, verbose_name='issued at')),
                ('metadata_json', models.JSONField(blank=True, default=dict, verbose_name='metadata')),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitation_batches', to='form_collection.formcollection')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_collection_batches', to=settings.AUTH_USER_MODEL)),
                ('issued_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issued_collection_batches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'invitation batch',
                'verbose_name_plural': 'invitation batches',
            },
        ),
        migrations.AddField(
            model_name='forminvitation',
            name='invitation_batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='form_invitations', to='form_collection.invitationbatch'),
        ),
        migrations.CreateModel(
            name='UnlinkedFormSubmission',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('control_number_hash', models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='control number hash')),
                ('student_number_hash', models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='student number hash')),
                ('email_hash', models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='email hash')),
                ('name_snapshot', models.CharField(blank=True, max_length=255, null=True, verbose_name='name snapshot')),
                ('program_snapshot', models.CharField(blank=True, max_length=100, null=True, verbose_name='program snapshot')),
                ('submitted_inventory', models.BooleanField(default=False, verbose_name='submitted inventory')),
                ('student_match_status', models.CharField(choices=[('UNMATCHED', 'Unmatched'), ('MATCHED', 'Matched'), ('LINKED', 'Linked'), ('NEEDS_MANUAL_REVIEW', 'Needs Manual Review'), ('REJECTED', 'Rejected')], default='UNMATCHED', max_length=30, verbose_name='matching status')),
                ('matched_at', models.DateTimeField(blank=True, null=True, verbose_name='matched at')),
                ('linked_at', models.DateTimeField(blank=True, null=True, verbose_name='linked at')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='reviewed at')),
                ('metadata_json', models.JSONField(blank=True, default=dict, verbose_name='metadata')),
                ('linked_student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='unlinked_submissions', to='profiles.studentprofile')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_unlinked_submissions', to=settings.AUTH_USER_MODEL)),
                ('source_collection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='unlinked_submissions', to='form_collection.formcollection')),
                ('source_invitation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='unlinked_submissions', to='form_collection.forminvitation')),
            ],
            options={
                'verbose_name': 'unlinked student record',
                'verbose_name_plural': 'unlinked student records',
            },
        ),
        migrations.AddField(
            model_name='forminvitation',
            name='unlinked_submission',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='form_invitations', to='form_collection.unlinkedformsubmission'),
        ),
        migrations.AddIndex(
            model_name='formcollection',
            index=models.Index(fields=['status'], name='form_collec_status_2b92d4_idx'),
        ),
        migrations.AddIndex(
            model_name='formcollection',
            index=models.Index(fields=['form_type'], name='form_collec_form_ty_f8e3bf_idx'),
        ),
        migrations.AddIndex(
            model_name='formcollection',
            index=models.Index(fields=['start_at', 'end_at'], name='form_collec_start_a_0a1cb0_idx'),
        ),
        migrations.AddIndex(
            model_name='unlinkedformsubmission',
            index=models.Index(fields=['student_match_status'], name='form_collec_student_a62c71_idx'),
        ),
        migrations.AddIndex(
            model_name='forminvitation',
            index=models.Index(fields=['status'], name='form_collec_status_24bfa2_idx'),
        ),
        migrations.AddIndex(
            model_name='forminvitation',
            index=models.Index(fields=['expires_at'], name='form_collec_expires_84320a_idx'),
        ),
    ]
