# Generated by Django 5.2.17 on 2026-09-07 14:06

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('form_collection', '0001_initial'),
        ('organizations', '0001_initial'),
        ('profiles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GraduateTracerResponse',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reference_code', models.CharField(db_index=True, help_text='Canonical GTS reference code.', max_length=50, unique=True, verbose_name='reference code')),
                ('lifecycle_snapshot', models.CharField(blank=True, max_length=50, verbose_name='lifecycle snapshot')),
                ('graduation_year', models.CharField(blank=True, db_index=True, max_length=20, verbose_name='graduation year')),
                ('program_snapshot', models.CharField(blank=True, max_length=100, verbose_name='program snapshot')),
                ('college_snapshot', models.CharField(blank=True, max_length=100, verbose_name='college snapshot')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('REOPENED_FOR_CORRECTION', 'Reopened for Correction'), ('VOIDED', 'Voided'), ('ARCHIVED', 'Archived')], db_index=True, default='DRAFT', max_length=30, verbose_name='status')),
                ('employment_status', models.CharField(blank=True, choices=[('EMPLOYED', 'Employed'), ('UNEMPLOYED', 'Unemployed'), ('NEVER_EMPLOYED', 'Never Employed'), ('SELF_EMPLOYED', 'Self Employed')], db_index=True, max_length=30, verbose_name='employment status')),
                ('first_job_related', models.BooleanField(blank=True, null=True, verbose_name='first job related')),
                ('job_relevance_summary', models.CharField(blank=True, max_length=255, verbose_name='job relevance summary')),
                ('telephone_number', models.CharField(blank=True, max_length=30, verbose_name='telephone number')),
                ('sex', models.CharField(blank=True, db_index=True, max_length=10, verbose_name='sex')),
                ('region_of_origin', models.CharField(blank=True, db_index=True, max_length=30, verbose_name='region of origin')),
                ('province', models.CharField(blank=True, max_length=100, verbose_name='province')),
                ('received_honors', models.BooleanField(blank=True, null=True, verbose_name='received honors')),
                ('presently_employed', models.CharField(blank=True, db_index=True, max_length=20, verbose_name='presently employed')),
                ('present_employment_category', models.CharField(blank=True, db_index=True, max_length=30, verbose_name='present employment category')),
                ('business_line', models.CharField(blank=True, db_index=True, max_length=50, verbose_name='major line of business')),
                ('place_of_work', models.CharField(blank=True, max_length=10, verbose_name='place of work')),
                ('is_first_job', models.BooleanField(blank=True, null=True, verbose_name='is first job')),
                ('first_job_search_duration', models.CharField(blank=True, db_index=True, max_length=40, verbose_name='first job search duration')),
                ('first_job_level', models.CharField(blank=True, max_length=40, verbose_name='first job level')),
                ('current_job_level', models.CharField(blank=True, max_length=40, verbose_name='current job level')),
                ('initial_gross_earnings', models.CharField(blank=True, max_length=40, verbose_name='initial gross monthly earnings')),
                ('curriculum_relevant', models.BooleanField(blank=True, null=True, verbose_name='curriculum relevant')),
                ('is_paper_transcription', models.BooleanField(default=False, verbose_name='paper transcription')),
                ('contact_listing_consent', models.BooleanField(default=False, verbose_name='contact listing consent')),
                ('consent_given_at', models.DateTimeField(blank=True, null=True, verbose_name='consent given at')),
                ('submitted_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='submitted at')),
                ('reopened_at', models.DateTimeField(blank=True, null=True, verbose_name='reopened at')),
                ('reopen_reason', models.TextField(blank=True, verbose_name='reopen reason')),
                ('voided_at', models.DateTimeField(blank=True, null=True, verbose_name='voided at')),
                ('void_reason', models.TextField(blank=True, verbose_name='void reason')),
                ('response_json', models.JSONField(blank=True, default=dict, verbose_name='response json')),
                ('metadata_json', models.JSONField(blank=True, default=dict, verbose_name='metadata json')),
                ('form_collection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gts_responses', to='form_collection.formcollection')),
                ('form_family', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='gts_responses', to='organizations.formfamily')),
                ('form_invitation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gts_responses', to='form_collection.forminvitation')),
                ('form_revision', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='gts_responses', to='organizations.formrevision')),
                ('reopened_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reopened_gts', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gts_responses', to='profiles.studentprofile')),
                ('transcribed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transcribed_gts', to=settings.AUTH_USER_MODEL)),
                ('unlinked_submission', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gts_responses', to='form_collection.unlinkedformsubmission')),
                ('voided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='voided_gts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'graduate tracer response',
                'verbose_name_plural': 'graduate tracer responses',
                'indexes': [models.Index(fields=['status', 'submitted_at'], name='graduate_tr_status_22eafd_idx'), models.Index(fields=['employment_status'], name='graduate_tr_employm_2f351b_idx'), models.Index(fields=['graduation_year', 'status'], name='graduate_tr_graduat_dda729_idx'), models.Index(fields=['presently_employed'], name='graduate_tr_present_b01be7_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status__in', ['DRAFT', 'SUBMITTED', 'REOPENED_FOR_CORRECTION']), ('student__isnull', False)), fields=('student', 'form_revision'), name='uniq_active_gts_student_revision'), models.UniqueConstraint(condition=models.Q(('status__in', ['DRAFT', 'SUBMITTED', 'REOPENED_FOR_CORRECTION']), ('unlinked_submission__isnull', False)), fields=('unlinked_submission', 'form_revision'), name='uniq_active_gts_unlinked_revision')],
            },
        ),
    ]
