"""Canonical report-definition catalog for the approved aggregate families."""

from apps.reports.choices import ReportFamilyChoices, SensitivityLevel, SuppressionMode


REPORT_DEFINITIONS = (
    {
        "key": "students_profile",
        "title": "Students' Profile Report",
        "description": (
            "Historical, privacy-protected student profiling distributions by dynamic "
            "program cohort. The historical CCMS document remains source-form context "
            "only; this report is reusable across institutions."
        ),
        "family": ReportFamilyChoices.STUDENT_PROFILE_INVENTORY,
        "sensitivity_level": SensitivityLevel.SENSITIVE,
        "requires_suppression": True,
        "default_suppression_threshold": 5,
        "suppression_mode": SuppressionMode.SECTION,
        "metadata_json": {
            "source_form_context": "Historical CCMS sample format; generic institutional profiling",
            "structural_reference": True,
            "document_template_key": "students_profile",
        },
    },
    {
        "key": "feedback_csm_aggregate",
        "title": "Client Satisfaction Measurement (CSM) Aggregate Report",
        "description": "Privacy-protected service-quality aggregates from CSM responses.",
        "family": ReportFamilyChoices.FEEDBACK_CSM,
        "sensitivity_level": SensitivityLevel.SENSITIVE,
        "requires_suppression": True,
        "default_suppression_threshold": 5,
        "suppression_mode": SuppressionMode.DISCLOSURE_SET,
    },
    {
        "key": "exit_interview_completion_summary",
        "title": "Exit Interview Completion Summary",
        "description": "Cohort-safe Exit Interview completion, eligibility, and source-form outcome aggregates.",
        "family": ReportFamilyChoices.EXIT_INTERVIEW,
        "sensitivity_level": SensitivityLevel.SENSITIVE,
        "requires_suppression": True,
        "default_suppression_threshold": 5,
        "suppression_mode": SuppressionMode.CELL,
    },
    {
        "key": "graduate_tracer_outcomes_summary",
        "title": "Graduate Tracer Outcomes Summary",
        "description": "Aggregate employment, examination, training, and education outcomes without contact-list data.",
        "family": ReportFamilyChoices.GRADUATE_TRACER,
        "sensitivity_level": SensitivityLevel.SENSITIVE,
        "requires_suppression": True,
        "default_suppression_threshold": 5,
        "suppression_mode": SuppressionMode.CELL,
    },
    {
        "key": "form_collection_progress_summary",
        "title": "Form Collection Progress Summary",
        "description": "Aggregate collection-token lifecycle and submission progress.",
        "family": ReportFamilyChoices.FORM_COLLECTION_PROGRESS,
        "sensitivity_level": SensitivityLevel.INTERNAL,
        "requires_suppression": True,
        "default_suppression_threshold": 5,
        "suppression_mode": SuppressionMode.CELL,
    },
    {
        "key": "document_requests_summary",
        "title": "Good Moral & Document Requests Summary",
        "description": "Aggregate document-request workflow and generated-document counts.",
        "family": ReportFamilyChoices.DOCUMENT_REQUESTS,
        "sensitivity_level": SensitivityLevel.SENSITIVE,
        "requires_suppression": True,
        "default_suppression_threshold": 5,
        "suppression_mode": SuppressionMode.CELL,
    },
    {
        "key": "appointments_counseling_workload_summary",
        "title": "Appointments & Counseling Workload Summary",
        "description": "Connected appointment-to-session workload, status, and outcome aggregates.",
        "family": ReportFamilyChoices.APPOINTMENTS_COUNSELING_WORKLOAD,
        "sensitivity_level": SensitivityLevel.SENSITIVE,
        "requires_suppression": True,
        "default_suppression_threshold": 5,
        "suppression_mode": SuppressionMode.CELL,
    },
    {
        "key": "referrals_call_slips_summary",
        "title": "Referrals & Call Slips Summary",
        "description": "Aggregate referral actions, call-slip outcomes, and explicitly linked session conversions.",
        "family": ReportFamilyChoices.REFERRALS_CALL_SLIPS,
        "sensitivity_level": SensitivityLevel.SENSITIVE,
        "requires_suppression": True,
        "default_suppression_threshold": 5,
        "suppression_mode": SuppressionMode.CELL,
    },
    {
        "key": "public_contact_summary",
        "title": "Public Contact & Suggestion Box Summary",
        "description": "Aggregate public-contact submission types, affiliations, and workflow statuses.",
        "family": ReportFamilyChoices.PUBLIC_CONTACT,
        "sensitivity_level": SensitivityLevel.INTERNAL,
        "requires_suppression": True,
        "default_suppression_threshold": 5,
        "suppression_mode": SuppressionMode.CELL,
    },
    {
        "key": "workflow_notifications_summary",
        "title": "Workflow & Notification Metrics Summary",
        "description": "Operational notification, outbox, and idempotency status metrics.",
        "family": ReportFamilyChoices.WORKFLOW_NOTIFICATIONS,
        "sensitivity_level": SensitivityLevel.INTERNAL,
        "requires_suppression": False,
        "default_suppression_threshold": 5,
        "suppression_mode": SuppressionMode.NONE,
    },
    {
        "key": "audit_report_access_summary",
        "title": "Audit & Report Access Summary",
        "description": "Aggregate report and data-access audit actions by safe action and role metadata.",
        "family": ReportFamilyChoices.AUDIT_REPORT_ACCESS,
        "sensitivity_level": SensitivityLevel.RESTRICTED,
        "requires_suppression": False,
        "default_suppression_threshold": 5,
        "suppression_mode": SuppressionMode.NONE,
    },
)
