# Generated by Django 5.2.17 on 2026-09-07 14:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ErrorEventCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('period_key', models.CharField(help_text="Calendar year, e.g. '2026'.", max_length=10, unique=True, verbose_name='period key')),
                ('last_sequence', models.PositiveIntegerField(default=0, verbose_name='last sequence')),
            ],
            options={
                'verbose_name': 'error event counter',
                'verbose_name_plural': 'error event counters',
            },
        ),
        migrations.CreateModel(
            name='ApplicationErrorEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('error_id', models.CharField(help_text='User-safe Error ID, e.g. ERR-2026-000001.', max_length=32, unique=True, verbose_name='error id')),
                ('trace_id', models.CharField(blank=True, help_text='Optional correlation/trace identifier.', max_length=100, null=True, verbose_name='trace id')),
                ('request_id', models.CharField(blank=True, help_text='Optional HTTP request correlation identifier.', max_length=100, null=True, verbose_name='request id')),
                ('severity', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('error', 'Error'), ('critical', 'Critical')], default='error', max_length=20, verbose_name='severity')),
                ('category', models.CharField(choices=[('validation', 'Validation'), ('permission', 'Permission'), ('external_service', 'External Service'), ('background_job', 'Background Job'), ('database', 'Database'), ('security', 'Security'), ('unknown', 'Unknown')], default='unknown', max_length=40, verbose_name='category')),
                ('environment', models.CharField(choices=[('development', 'Development'), ('testing', 'Testing'), ('staging', 'Staging'), ('production', 'Production')], default='production', max_length=20, verbose_name='environment')),
                ('release_version', models.CharField(blank=True, help_text='Optional release/version label from settings/env.', max_length=64, null=True, verbose_name='release version')),
                ('build_id', models.CharField(blank=True, help_text='Immutable deployment build identifier from release identity.', max_length=128, null=True, verbose_name='build identifier')),
                ('app_label', models.CharField(blank=True, help_text='Django app label where the error originated, if known.', max_length=100, null=True, verbose_name='app label')),
                ('route_name', models.CharField(blank=True, help_text='URL route name, if available.', max_length=255, null=True, verbose_name='route name')),
                ('view_name', models.CharField(blank=True, help_text='View/module name, if available.', max_length=255, null=True, verbose_name='view name')),
                ('http_method', models.CharField(blank=True, help_text='HTTP method, if applicable.', max_length=10, null=True, verbose_name='http method')),
                ('path_template', models.CharField(blank=True, help_text='Sanitized, parameterized path template. No raw query strings.', max_length=255, null=True, verbose_name='path template')),
                ('status_code', models.IntegerField(blank=True, help_text='HTTP status code, if applicable.', null=True, verbose_name='status code')),
                ('actor_role', models.CharField(blank=True, help_text="Snapshot of the actor's COMPASS role.", max_length=50, null=True, verbose_name='actor role')),
                ('actor_ip_hash', models.CharField(blank=True, help_text='HMAC hash of actor IP. Raw IP is never stored.', max_length=64, null=True, verbose_name='actor ip hash')),
                ('user_agent_hash', models.CharField(blank=True, help_text='HMAC hash of User-Agent. Raw UA is never stored.', max_length=64, null=True, verbose_name='user agent hash')),
                ('related_reference_code', models.CharField(blank=True, help_text='Safe workflow reference code, e.g. DOC-AY2526-000001.', max_length=50, null=True, verbose_name='related reference code')),
                ('related_object_type', models.CharField(blank=True, help_text='Safe model label, e.g. counseling.StudentSession.', max_length=100, null=True, verbose_name='related object type')),
                ('related_object_id', models.CharField(blank=True, help_text='Safe internal reference only. No sensitive identifiers.', max_length=100, null=True, verbose_name='related object id')),
                ('exception_class', models.CharField(blank=True, help_text='Exception class name only. Never raw exception text.', max_length=255, null=True, verbose_name='exception class')),
                ('safe_message', models.CharField(help_text='Generic, bounded, privacy-safe message selected by category.', max_length=255, verbose_name='safe message')),
                ('redacted_stack_trace', models.TextField(blank=True, help_text='Environment-gated. Must be NULL in production unless explicitly approved. Never shown to normal users.', null=True, verbose_name='redacted stack trace')),
                ('metadata_json', models.JSONField(default=dict, help_text='Sanitized safe JSON only. No secrets/private content.', verbose_name='metadata')),
                ('is_resolved', models.BooleanField(default=False, help_text='Whether an IT Admin has marked this error resolved.', verbose_name='is resolved')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='resolved at')),
                ('resolution_note', models.CharField(blank=True, help_text='Bounded, sanitized resolution note. No sensitive content.', max_length=255, verbose_name='resolution note')),
                ('actor_user', models.ForeignKey(blank=True, help_text='Authenticated actor at time of error, if any.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='application_error_events', to=settings.AUTH_USER_MODEL)),
                ('resolved_by', models.ForeignKey(blank=True, help_text='IT Admin who resolved this error.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_application_error_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'application error event',
                'verbose_name_plural': 'application error events',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['error_id'], name='system_appl_error_i_eda671_idx'), models.Index(fields=['created_at'], name='system_appl_created_ff8041_idx'), models.Index(fields=['severity'], name='system_appl_severit_e32b03_idx'), models.Index(fields=['category'], name='system_appl_categor_fdac50_idx'), models.Index(fields=['environment'], name='system_appl_environ_270e09_idx'), models.Index(fields=['is_resolved'], name='system_appl_is_reso_5d060c_idx'), models.Index(fields=['app_label'], name='system_appl_app_lab_6271ae_idx'), models.Index(fields=['related_reference_code'], name='system_appl_related_775ce2_idx')],
            },
        ),
        migrations.CreateModel(
            name='MaintenanceWindow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('active', 'Active'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], db_index=True, default='scheduled', max_length=20, verbose_name='status')),
                ('starts_at', models.DateTimeField(db_index=True, verbose_name='starts at')),
                ('ends_at', models.DateTimeField(db_index=True, verbose_name='ends at')),
                ('safe_public_message', models.TextField(blank=True, help_text='Sanitized public message shown to users during maintenance.', verbose_name='safe public message')),
                ('internal_reason_code', models.CharField(blank=True, help_text='Sanitized code describing internal reason, e.g. DB_UPGRADE.', max_length=100, verbose_name='internal reason code')),
                ('activated_by', models.ForeignKey(blank=True, help_text='Admin user who activated the maintenance.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activated_maintenance_windows', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, help_text='Admin user who scheduled the maintenance.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_maintenance_windows', to=settings.AUTH_USER_MODEL)),
                ('deactivated_by', models.ForeignKey(blank=True, help_text='Admin user who completed/deactivated the maintenance.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deactivated_maintenance_windows', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'maintenance window',
                'verbose_name_plural': 'maintenance windows',
                'ordering': ['-starts_at'],
                'constraints': [models.CheckConstraint(condition=models.Q(('ends_at__gt', models.F('starts_at'))), name='maintenance_window_ends_after_starts'), models.UniqueConstraint(condition=models.Q(('status', 'active')), fields=('status',), name='maintenance_window_one_active')],
            },
        ),
        migrations.CreateModel(
            name='OperationalCommandRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('command_key', models.CharField(max_length=100, verbose_name='command key')),
                ('mode', models.CharField(default='execute', max_length=20, verbose_name='mode')),
                ('actor_identity', models.CharField(blank=True, max_length=120, verbose_name='actor or system identity')),
                ('environment', models.CharField(max_length=40, verbose_name='environment')),
                ('reason_code', models.CharField(max_length=100, verbose_name='reason code')),
                ('configuration_identifier', models.CharField(blank=True, max_length=160, verbose_name='configuration identifier')),
                ('started_at', models.DateTimeField(verbose_name='started at')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='finished at')),
                ('outcome', models.CharField(default='STARTED', max_length=30, verbose_name='outcome')),
                ('outcome_reason_code', models.CharField(blank=True, max_length=100, verbose_name='outcome reason code')),
                ('release_version', models.CharField(blank=True, max_length=64, verbose_name='release version')),
                ('build_id', models.CharField(blank=True, max_length=128, verbose_name='build identifier')),
                ('summary_json', models.JSONField(blank=True, default=dict, verbose_name='allowlisted summary')),
                ('actor_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operational_command_runs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-started_at', '-pk'],
                'indexes': [models.Index(fields=['command_key', 'started_at'], name='system_oper_command_489540_idx'), models.Index(fields=['outcome', 'started_at'], name='system_oper_outcome_f6bc7d_idx')],
            },
        ),
    ]
