# Generated by Django 5.2.17 on 2026-09-07 14:06

import apps.support_needs.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0001_initial'),
        ('security', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssessmentInstrument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.SlugField(help_text='Unique lowercase stable identifier.', max_length=100, unique=True, verbose_name='stable key')),
                ('title', models.CharField(help_text='Human-readable title of the assessment instrument.', max_length=200, verbose_name='display title')),
                ('category', models.CharField(choices=[('academic', 'Academic'), ('career', 'Career'), ('guidance', 'Guidance'), ('wellness_screening_non_diagnostic', 'Wellness Screening (Non-Diagnostic)'), ('office_approved_other', 'Office Approved Other')], max_length=50, verbose_name='category')),
                ('official_source_reference', models.CharField(blank=True, help_text='Safe reference to approved source specification, manual, or policy.', max_length=255, verbose_name='official source reference')),
                ('has_official_scoring_guide', models.BooleanField(default=False, verbose_name='has official scoring guide')),
                ('allows_scores', models.BooleanField(default=False, help_text='If true, score fields are permitted on records of this instrument.', verbose_name='allows scores')),
                ('allows_interpretation', models.BooleanField(default=True, help_text='If true, professional interpretation narrative/records are permitted.', verbose_name='allows interpretation')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('notes', models.TextField(blank=True, help_text='Safe governance notes regarding the instrument only.', verbose_name='notes')),
            ],
            options={
                'verbose_name': 'assessment instrument',
                'verbose_name_plural': 'assessment instruments',
                'indexes': [models.Index(fields=['category'], name='assessments_categor_9957b5_idx'), models.Index(fields=['is_active'], name='assessments_is_acti_cc5e7a_idx')],
            },
        ),
        migrations.CreateModel(
            name='StudentAssessmentRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('administered_at', models.DateTimeField(blank=True, null=True, verbose_name='administered at')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('recorded', 'Recorded'), ('under_review', 'Under Review'), ('reviewed', 'Reviewed'), ('released_to_student', 'Released to Student'), ('superseded', 'Superseded'), ('voided', 'Voided'), ('archived', 'Archived')], default='draft', max_length=50, verbose_name='status')),
                ('raw_score', models.CharField(blank=True, max_length=50, null=True, verbose_name='raw score')),
                ('scaled_score', models.CharField(blank=True, max_length=50, null=True, verbose_name='scaled score')),
                ('score_label', models.CharField(blank=True, help_text='Safe categorical label (e.g. High, Medium, Low) if non-diagnostic.', max_length=100, null=True, verbose_name='score label')),
                ('interpretation_text_encrypted', models.TextField(blank=True, help_text='Base64-encoded encrypted Fernet envelope for sensitive interpretation text.', null=True, verbose_name='interpretation text encrypted')),
                ('interpretation_visibility', models.CharField(choices=[('counselor_only', 'Counselor Only'), ('head_guidance_review', 'Head Guidance Review'), ('released_to_student_safe_summary', 'Released to Student Safe Summary')], default='counselor_only', max_length=50, verbose_name='interpretation visibility')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='reviewed at')),
                ('released_to_student', models.BooleanField(default=False, verbose_name='released to student')),
                ('released_to_student_at', models.DateTimeField(blank=True, null=True, verbose_name='released to student at')),
                ('source_form_reference', models.CharField(blank=True, max_length=100, null=True, verbose_name='source form reference')),
                ('metadata_json', models.JSONField(blank=True, null=True, validators=[apps.support_needs.models.validate_safe_keys], verbose_name='metadata json')),
                ('administered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='administered_assessments', to=settings.AUTH_USER_MODEL)),
                ('instrument', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_support_needs', to='assessments.assessmentinstrument')),
                ('protected_file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assessment_records', to='security.protectedfile')),
                ('released_to_student_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='released_assessments', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_assessments', to=settings.AUTH_USER_MODEL)),
                ('student_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessment_records', to='profiles.studentprofile')),
            ],
            options={
                'verbose_name': 'student assessment record',
                'verbose_name_plural': 'student assessment records',
                'indexes': [models.Index(fields=['student_profile'], name='assessments_student_4c460d_idx'), models.Index(fields=['instrument'], name='assessments_instrum_4d3c6e_idx'), models.Index(fields=['status'], name='assessments_status_7a6809_idx'), models.Index(fields=['administered_at'], name='assessments_adminis_735e4e_idx'), models.Index(fields=['administered_by'], name='assessments_adminis_1bdfe2_idx'), models.Index(fields=['reviewed_by'], name='assessments_reviewe_0c5dea_idx'), models.Index(fields=['released_to_student'], name='assessments_release_294935_idx')],
            },
        ),
    ]
