# Generated by Django 5.2.17 on 2026-09-07 14:06

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
        ('security', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('stable_key', models.SlugField(help_text="Unique slug for this template family, e.g. 'good_moral_student'.", max_length=80, unique=True, verbose_name='stable key')),
                ('display_name', models.CharField(max_length=255, verbose_name='display name')),
                ('document_kind', models.CharField(choices=[('CERTIFICATE', 'Certificate'), ('OFFICIAL_FORM', 'Official Form'), ('RELEASE_RECORD', 'Release Record'), ('REPORT_EXPORT', 'Report Export'), ('SUMMARY', 'Summary')], max_length=30, verbose_name='document kind')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('ACTIVE', 'Active'), ('RETIRED', 'Retired'), ('ARCHIVED', 'Archived')], default='DRAFT', max_length=20, verbose_name='status')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('default_output_format', models.CharField(choices=[('HTML', 'HTML'), ('PDF', 'PDF')], default='HTML', max_length=10, verbose_name='default output format')),
                ('retention_classification', models.CharField(choices=[('STANDARD', 'Standard'), ('OFFICIAL_RECORD', 'Official Record'), ('CONFIDENTIAL', 'Confidential'), ('TEMPORARY', 'Temporary')], default='STANDARD', max_length=30, verbose_name='retention classification')),
                ('access_policy_key', models.CharField(blank=True, help_text='Default access policy key for generated documents from this template.', max_length=100, verbose_name='access policy key')),
                ('source_notes', models.TextField(blank=True, verbose_name='source notes')),
                ('owner_office', models.ForeignKey(blank=True, help_text='Office that owns this template family.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_document_templates', to='organizations.officeprofile')),
                ('related_form_family', models.ForeignKey(blank=True, help_text='Related source form family, if applicable.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='document_templates', to='organizations.formfamily')),
            ],
            options={
                'verbose_name': 'document template',
                'verbose_name_plural': 'document templates',
            },
        ),
        migrations.CreateModel(
            name='DocumentTemplateVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version_label', models.CharField(help_text="Human-readable version label, e.g. 'v1.0'.", max_length=50, verbose_name='version label')),
                ('internal_template_version', models.CharField(default='1', help_text='COMPASS internal template version for this render configuration.', max_length=30, verbose_name='internal template version')),
                ('template_path', models.CharField(help_text="Path to the Django template file, e.g. 'documents/print/good_moral_student/v1.html'.", max_length=500, verbose_name='template path')),
                ('stylesheet_path', models.CharField(blank=True, help_text='Path to the print CSS stylesheet, if any.', max_length=500, verbose_name='stylesheet path')),
                ('renderer_backend', models.CharField(choices=[('HTML_ONLY', 'HTML Only'), ('PLAYWRIGHT_PDF', 'Playwright PDF')], default='HTML_ONLY', max_length=30, verbose_name='renderer backend')),
                ('output_format', models.CharField(choices=[('HTML', 'HTML'), ('PDF', 'PDF')], default='HTML', max_length=10, verbose_name='output format')),
                ('page_size', models.CharField(default='LETTER', help_text='Paper size, e.g. LETTER, A4, LEGAL.', max_length=30, verbose_name='page size')),
                ('page_orientation', models.CharField(default='portrait', help_text='Page orientation: portrait or landscape.', max_length=20, verbose_name='page orientation')),
                ('page_margins_json', models.JSONField(blank=True, default=dict, help_text="Margins in mm, e.g. {'top': 25, 'right': 25, 'bottom': 25, 'left': 25}.", verbose_name='page margins')),
                ('required_context_schema_json', models.JSONField(blank=True, default=dict, help_text='Metadata-only schema describing required context fields. Not a form builder.', verbose_name='required context schema')),
                ('institution_profile_snapshot', models.JSONField(blank=True, default=dict, verbose_name='institution profile snapshot')),
                ('office_profile_snapshot', models.JSONField(blank=True, default=dict, verbose_name='office profile snapshot')),
                ('brand_asset_snapshot', models.JSONField(blank=True, default=dict, verbose_name='brand asset snapshot')),
                ('form_revision_snapshot', models.JSONField(blank=True, default=dict, verbose_name='form revision snapshot')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('ACTIVE', 'Active'), ('RETIRED', 'Retired'), ('ARCHIVED', 'Archived')], default='DRAFT', max_length=20, verbose_name='status')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='approved at')),
                ('retired_at', models.DateTimeField(blank=True, null=True, verbose_name='retired at')),
                ('is_used', models.BooleanField(default=False, help_text='Set to True once any generated document references this version.', verbose_name='is used')),
                ('first_used_at', models.DateTimeField(blank=True, null=True, verbose_name='first used at')),
                ('template_checksum', models.CharField(blank=True, help_text='SHA-256 checksum of the template file, if computed.', max_length=64, verbose_name='template checksum')),
                ('source_notes', models.TextField(blank=True, verbose_name='source notes')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_document_template_versions', to=settings.AUTH_USER_MODEL)),
                ('related_form_revision', models.ForeignKey(blank=True, help_text='Related form revision for official forms.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='document_template_versions', to='organizations.formrevision')),
                ('retired_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='retired_document_template_versions', to=settings.AUTH_USER_MODEL)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='versions', to='documents.documenttemplate')),
            ],
            options={
                'verbose_name': 'document template version',
                'verbose_name_plural': 'document template versions',
            },
        ),
        migrations.CreateModel(
            name='GeneratedDocument',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reference_code', models.CharField(help_text='Generated DOC-prefix reference code. Lookup aid only, not authorization.', max_length=30, unique=True, verbose_name='reference code')),
                ('owning_app_label', models.CharField(blank=True, max_length=100, verbose_name='owning app label')),
                ('owning_model_name', models.CharField(blank=True, max_length=100, verbose_name='owning model name')),
                ('owning_object_id', models.CharField(blank=True, max_length=255, verbose_name='owning object id')),
                ('document_status', models.CharField(choices=[('DRAFT', 'Draft'), ('GENERATED', 'Generated'), ('RELEASED', 'Released'), ('VOIDED', 'Voided'), ('ARCHIVED', 'Archived'), ('FAILED', 'Failed')], default='DRAFT', max_length=20, verbose_name='document status')),
                ('generated_at', models.DateTimeField(blank=True, null=True, verbose_name='generated at')),
                ('released_at', models.DateTimeField(blank=True, null=True, verbose_name='released at')),
                ('voided_at', models.DateTimeField(blank=True, null=True, verbose_name='voided at')),
                ('void_reason_code', models.CharField(blank=True, help_text="Safe reason code for voiding, e.g. 'error', 'duplicate', 'superseded'.", max_length=50, verbose_name='void reason code')),
                ('generation_context_snapshot_json', models.JSONField(blank=True, default=dict, help_text='Audit-safe metadata snapshot of the generation context. No sensitive content.', verbose_name='generation context snapshot')),
                ('template_version_snapshot', models.JSONField(blank=True, default=dict, verbose_name='template version snapshot')),
                ('institution_profile_snapshot', models.JSONField(blank=True, default=dict, verbose_name='institution profile snapshot')),
                ('office_profile_snapshot', models.JSONField(blank=True, default=dict, verbose_name='office profile snapshot')),
                ('form_revision_snapshot', models.JSONField(blank=True, default=dict, verbose_name='form revision snapshot')),
                ('brand_asset_snapshot', models.JSONField(blank=True, default=dict, verbose_name='brand asset snapshot')),
                ('renderer_snapshot', models.JSONField(blank=True, default=dict, help_text='Renderer backend/version metadata at generation time.', verbose_name='renderer snapshot')),
                ('content_hash', models.CharField(blank=True, help_text='SHA-256 hash of the rendered output content.', max_length=64, verbose_name='content hash')),
                ('access_policy_key', models.CharField(blank=True, max_length=100, verbose_name='access policy key')),
                ('retention_hold', models.BooleanField(default=False, verbose_name='retention hold')),
                ('form_revision', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_documents', to='organizations.formrevision')),
                ('generated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_documents_by', to=settings.AUTH_USER_MODEL)),
                ('generated_for_user', models.ForeignKey(blank=True, help_text='User this document was generated for, if applicable.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_documents_for', to=settings.AUTH_USER_MODEL)),
                ('protected_file', models.ForeignKey(blank=True, help_text='Protected file storing the rendered output.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_documents', to='security.protectedfile')),
                ('released_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='released_documents', to=settings.AUTH_USER_MODEL)),
                ('template_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='generated_documents', to='documents.documenttemplateversion')),
                ('voided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='voided_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'generated document',
                'verbose_name_plural': 'generated documents',
            },
        ),
        migrations.AddIndex(
            model_name='documenttemplate',
            index=models.Index(fields=['status', 'document_kind'], name='documents_d_status_9f2b9c_idx'),
        ),
        migrations.AddIndex(
            model_name='documenttemplateversion',
            index=models.Index(fields=['template', 'status'], name='documents_d_templat_51b418_idx'),
        ),
        migrations.AddConstraint(
            model_name='documenttemplateversion',
            constraint=models.UniqueConstraint(fields=('template', 'version_label', 'internal_template_version'), name='unique_template_version_tuple'),
        ),
        migrations.AddConstraint(
            model_name='documenttemplateversion',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'ACTIVE')), fields=('template',), name='unique_active_template_version_per_template'),
        ),
        migrations.AddIndex(
            model_name='generateddocument',
            index=models.Index(fields=['document_status'], name='documents_g_documen_43c7ec_idx'),
        ),
        migrations.AddIndex(
            model_name='generateddocument',
            index=models.Index(fields=['reference_code'], name='documents_g_referen_2a3e37_idx'),
        ),
        migrations.AddIndex(
            model_name='generateddocument',
            index=models.Index(fields=['owning_app_label', 'owning_model_name', 'owning_object_id'], name='documents_g_owning__bb43e3_idx'),
        ),
        migrations.AddIndex(
            model_name='generateddocument',
            index=models.Index(fields=['template_version', 'document_status'], name='documents_g_templat_897440_idx'),
        ),
    ]
