# Generated by Django 5.2.17 on 2026-09-07 14:06

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('form_collection', '0001_initial'),
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CSMInvitation',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('service_family', models.CharField(choices=[('COUNSELING', 'Counseling'), ('CALL_SLIP', 'Call Slip Assistance'), ('GOOD_MORAL', 'Good Moral Certificate'), ('REFERRAL', 'Referral Assistance')], max_length=30)),
                ('service_label', models.CharField(max_length=100)),
                ('service_category', models.CharField(max_length=100)),
                ('related_workflow_type', models.CharField(max_length=100)),
                ('related_reference_code', models.CharField(max_length=50)),
                ('completion_event_key', models.CharField(max_length=255, unique=True)),
                ('completed_at', models.DateTimeField()),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('status', models.CharField(choices=[('AVAILABLE', 'Available'), ('SUBMITTED', 'Submitted'), ('EXPIRED', 'Expired')], db_index=True, default='AVAILABLE', max_length=20)),
                ('first_sent_at', models.DateTimeField(blank=True, null=True)),
                ('last_sent_at', models.DateTimeField(blank=True, null=True)),
                ('send_count', models.PositiveIntegerField(default=0)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('issued_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issued_csm_invitations', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='csm_invitations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-completed_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FeedbackSubmission',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reference_code', models.CharField(db_index=True, help_text='Canonical FBK reference code.', max_length=50, unique=True, verbose_name='reference code')),
                ('client_type', models.CharField(blank=True, help_text='Demographic client type (e.g. Citizen, Business, Government).', max_length=50, verbose_name='client type')),
                ('lifecycle_snapshot', models.CharField(blank=True, help_text='Frozen lifecycle status of respondent at time of submission.', max_length=50, null=True, verbose_name='lifecycle snapshot')),
                ('is_anonymous', models.BooleanField(default=False, verbose_name='is anonymous')),
                ('source', models.CharField(choices=[('PUBLIC', 'Public'), ('AUTHENTICATED', 'Authenticated'), ('TOKEN', 'Token'), ('STAFF_ENCODED', 'Staff Encoded'), ('SERVICE_INVITATION', 'Service invitation')], default='PUBLIC', max_length=30, verbose_name='source')),
                ('service_category', models.CharField(help_text=' GTAO service availed (e.g. Counseling, Admission, Testing, etc.)', max_length=100, verbose_name='service category')),
                ('related_workflow_type', models.CharField(blank=True, help_text='Workflow app boundary key, e.g. appointments, referrals.', max_length=100, null=True, verbose_name='related workflow type')),
                ('related_reference_code', models.CharField(blank=True, help_text='Reference code of the related transaction (e.g., APT-AY2526-000001).', max_length=50, null=True, verbose_name='related reference code')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('REVIEWED', 'Reviewed'), ('RESPONDED', 'Responded'), ('CLOSED', 'Closed'), ('SPAM', 'Spam'), ('ARCHIVED', 'Archived'), ('VOIDED', 'Voided')], db_index=True, default='DRAFT', max_length=30, verbose_name='status')),
                ('submitted_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='submitted at')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='reviewed at')),
                ('closed_at', models.DateTimeField(blank=True, null=True, verbose_name='closed at')),
                ('overall_satisfaction', models.PositiveIntegerField(blank=True, help_text='Overall client satisfaction score.', null=True, verbose_name='overall satisfaction')),
                ('sqd_average', models.FloatField(blank=True, help_text='Average rating across Service Quality Dimensions.', null=True, verbose_name='sqd average')),
                ('sqd0', models.PositiveSmallIntegerField(blank=True, help_text='SQD0 satisfied with service.', null=True, verbose_name='sqd0')),
                ('sqd1', models.PositiveSmallIntegerField(blank=True, help_text='SQD1 reasonable time.', null=True, verbose_name='sqd1')),
                ('sqd2', models.PositiveSmallIntegerField(blank=True, help_text='SQD2 followed requirements.', null=True, verbose_name='sqd2')),
                ('sqd3', models.PositiveSmallIntegerField(blank=True, help_text='SQD3 easy and simple steps.', null=True, verbose_name='sqd3')),
                ('sqd4', models.PositiveSmallIntegerField(blank=True, help_text='SQD4 found transaction info.', null=True, verbose_name='sqd4')),
                ('sqd5', models.PositiveSmallIntegerField(blank=True, help_text='SQD5 reasonable fees.', null=True, verbose_name='sqd5')),
                ('sqd6', models.PositiveSmallIntegerField(blank=True, help_text='SQD6 office was fair.', null=True, verbose_name='sqd6')),
                ('sqd7', models.PositiveSmallIntegerField(blank=True, help_text='SQD7 treated courteously.', null=True, verbose_name='sqd7')),
                ('sqd8', models.PositiveSmallIntegerField(blank=True, help_text='SQD8 got what was needed.', null=True, verbose_name='sqd8')),
                ('sq_personnel_helpfulness', models.PositiveSmallIntegerField(blank=True, help_text='Part 1 IV-1: accommodating, attentive and helpfulness.', null=True, verbose_name='personnel helpfulness')),
                ('sq_personnel_competence', models.PositiveSmallIntegerField(blank=True, help_text='Part 1 IV-2: knows the job well.', null=True, verbose_name='personnel competence')),
                ('sq_personnel_flexibility', models.PositiveSmallIntegerField(blank=True, help_text='Part 1 IV-3: flexible in handling request.', null=True, verbose_name='personnel flexibility')),
                ('sq_personnel_accuracy', models.PositiveSmallIntegerField(blank=True, help_text='Part 1 IV-4: gave accurate information.', null=True, verbose_name='personnel accuracy')),
                ('sq_personnel_appearance', models.PositiveSmallIntegerField(blank=True, help_text='Part 1 IV-5: appearance of service personnel.', null=True, verbose_name='personnel appearance')),
                ('sq_personnel_delivered', models.PositiveSmallIntegerField(blank=True, help_text='Part 1 IV-6: delivered what was committed.', null=True, verbose_name='personnel delivered')),
                ('op_located', models.PositiveSmallIntegerField(blank=True, help_text='Part 1 V-1: conveniently located and easy to find.', null=True, verbose_name='premises located')),
                ('op_cleanliness', models.PositiveSmallIntegerField(blank=True, help_text='Part 1 V-2: cleanliness of the premises.', null=True, verbose_name='premises cleanliness')),
                ('op_environment', models.PositiveSmallIntegerField(blank=True, help_text='Part 1 V-3: conducive working environment.', null=True, verbose_name='premises environment')),
                ('op_office_hours', models.PositiveSmallIntegerField(blank=True, help_text='Part 1 V-4: convenient office hours.', null=True, verbose_name='premises office hours')),
                ('op_availability', models.PositiveSmallIntegerField(blank=True, help_text='Part 1 V-5: availability of the service of the personnel.', null=True, verbose_name='premises availability')),
                ('cc_awareness', models.CharField(blank=True, help_text='CC1 answer choice.', max_length=100, verbose_name='cc awareness')),
                ('cc_visibility', models.CharField(blank=True, help_text='CC2 answer choice.', max_length=100, verbose_name='cc visibility')),
                ('cc_helpfulness', models.CharField(blank=True, help_text='CC3 answer choice.', max_length=100, verbose_name='cc helpfulness')),
                ('sex', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('PREFER_NOT', 'Prefer not to say')], help_text='CSM Part 2 demographic sex question.', max_length=20, verbose_name='sex')),
                ('age', models.PositiveSmallIntegerField(blank=True, help_text='CSM Part 2 demographic age.', null=True, verbose_name='age')),
                ('region_of_residence', models.CharField(blank=True, help_text='CSM Part 2 region of residence.', max_length=100, verbose_name='region of residence')),
                ('talked_to_counselor', models.BooleanField(blank=True, help_text='Part 1 II: whether the respondent spoke with the Guidance Counselor.', null=True, verbose_name='talked to counselor')),
                ('accommodated_by', models.CharField(blank=True, help_text='Part 1 II: who accommodated the respondent if not the counselor.', max_length=100, verbose_name='accommodated by')),
                ('visit_count', models.PositiveSmallIntegerField(blank=True, help_text='Part 1 III: how many times the respondent visited the office.', null=True, verbose_name='visit count')),
                ('transaction_duration_text', models.CharField(blank=True, help_text='Part 1: free-text duration the respondent took to finish the transaction.', max_length=100, verbose_name='transaction duration')),
                ('response_json', models.JSONField(blank=True, default=dict, help_text='Restricted full survey response body.', verbose_name='response json')),
                ('comment_text', models.TextField(blank=True, help_text='Restricted open-ended comment or suggestions.', verbose_name='comment text')),
                ('experience_feedback', models.TextField(blank=True, help_text="Restricted open-ended feedback about the respondent's experience.", verbose_name='experience feedback')),
                ('metadata_json', models.JSONField(blank=True, default=dict, help_text='Non-PII audit-safe metadata.', verbose_name='metadata json')),
                ('is_paper_transcription', models.BooleanField(default=False, help_text='Marks a response transcribed from a paper form by office staff.', verbose_name='is paper transcription')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_feedbacks', to=settings.AUTH_USER_MODEL)),
                ('form_collection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feedback_submissions', to='form_collection.formcollection')),
                ('form_family', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='feedback_submissions', to='organizations.formfamily')),
                ('form_invitation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feedback_submissions', to='form_collection.forminvitation')),
                ('form_revision', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='feedback_submissions', to='organizations.formrevision')),
                ('invitation', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='submission', to='feedback.csminvitation')),
                ('respondent_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feedback_submissions', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_feedbacks', to=settings.AUTH_USER_MODEL)),
                ('transcribed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transcribed_feedbacks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'feedback submission',
                'verbose_name_plural': 'feedback submissions',
            },
        ),
        migrations.AddIndex(
            model_name='csminvitation',
            index=models.Index(fields=['student', 'status', 'expires_at'], name='feedback_cs_student_c5e977_idx'),
        ),
        migrations.AddIndex(
            model_name='csminvitation',
            index=models.Index(fields=['service_family', 'completed_at'], name='feedback_cs_service_6e4a9c_idx'),
        ),
        migrations.AddIndex(
            model_name='csminvitation',
            index=models.Index(fields=['related_workflow_type', 'related_reference_code'], name='feedback_cs_related_f8cdef_idx'),
        ),
        migrations.AddConstraint(
            model_name='csminvitation',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'SUBMITTED'), ('submitted_at__isnull', False)), models.Q(('status', 'SUBMITTED'), _negated=True), _connector='OR'), name='csm_submitted_requires_timestamp'),
        ),
        migrations.AddIndex(
            model_name='feedbacksubmission',
            index=models.Index(fields=['status', 'submitted_at'], name='feedback_fe_status_1aae85_idx'),
        ),
        migrations.AddIndex(
            model_name='feedbacksubmission',
            index=models.Index(fields=['reference_code'], name='feedback_fe_referen_3cdf5f_idx'),
        ),
        migrations.AddIndex(
            model_name='feedbacksubmission',
            index=models.Index(fields=['service_category'], name='feedback_fe_service_02e97b_idx'),
        ),
        migrations.AddConstraint(
            model_name='feedbacksubmission',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('source', 'SERVICE_INVITATION'), _negated=True), models.Q(('invitation__isnull', False), ('related_workflow_type__isnull', False), models.Q(('related_workflow_type', ''), _negated=True), ('related_reference_code__isnull', False), models.Q(('related_reference_code', ''), _negated=True)), _connector='OR'), name='feedback_service_source_requires_invitation'),
        ),
    ]
