"""Server-owned request and trace correlation for HTTP boundaries."""

from __future__ import annotations

import secrets
import re

from apps.common.api.constants import API_MAX_CORRELATION_ID_LENGTH


_CORRELATION_RE = re.compile(r"\A[A-Za-z0-9][A-Za-z0-9._:-]{0,99}\Z")


def validate_trace_id(value: object) -> str | None:
    """Return a bounded trace identifier or ``None``.

    Trace IDs may be propagated, but request IDs are always generated by the
    server.  This prevents a caller from selecting another request's public
    correlation identifier.
    """

    if value is None:
        return None
    candidate = str(value).strip()
    if not candidate or len(candidate) > API_MAX_CORRELATION_ID_LENGTH:
        return None
    if not _CORRELATION_RE.fullmatch(candidate):
        return None
    return candidate


def new_request_id() -> str:
    return f"REQ-{secrets.token_hex(16).upper()}"


def attach_request_correlation(request) -> None:
    """Attach server-owned correlation facts to a request object."""

    if getattr(request, "_compass_request_id", None):
        return
    request._compass_request_id = new_request_id()
    request._compass_trace_id = validate_trace_id(
        (getattr(request, "META", {}) or {}).get("HTTP_X_TRACE_ID")
    )


def request_id(request) -> str:
    attach_request_correlation(request)
    return request._compass_request_id


def trace_id(request) -> str | None:
    attach_request_correlation(request)
    return request._compass_trace_id
