# Generated by Django 5.2.17 on 2026-09-07 14:06

import apps.security.fields
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentInventorySnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('academic_year', models.CharField(help_text="The academic year of this snapshot, e.g., '2025-2026'.", max_length=50)),
                ('schema_key', models.CharField(default='individual-inventory-v2', help_text='Key identifying the structure/family of the form.', max_length=100)),
                ('schema_version', models.CharField(default='2.1.0', help_text='Semantic version code of the form schema.', max_length=50)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('REOPENED_FOR_CORRECTION', 'Reopened for Correction')], default='DRAFT', help_text='The current workflow state of the inventory.', max_length=50)),
                ('data', models.JSONField(default=dict, help_text='Confidential questionnaire answer dictionary.')),
                ('data_encrypted', apps.security.fields.EncryptedJSONField(blank=True, default=None, null=True)),
                ('submitted_at', models.DateTimeField(blank=True, help_text='Timestamp when the student submitted this snapshot.', null=True)),
                ('reopened_at', models.DateTimeField(blank=True, help_text='Timestamp when an authorized user reopened this snapshot for corrections.', null=True)),
                ('reopen_reason', models.TextField(blank=True, help_text='The justification captured when this record was reopened.')),
                ('reopen_reason_encrypted', apps.security.fields.EncryptedTextField(blank=True, default=None, null=True)),
                ('correction_notes', models.TextField(blank=True, help_text='Internal notes concerning the requested correction or verification.')),
                ('correction_notes_encrypted', apps.security.fields.EncryptedTextField(blank=True, default=None, null=True)),
                ('reopened_by', models.ForeignKey(blank=True, help_text='The counselor or staff member who authorized reopening this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reopened_inventories', to=settings.AUTH_USER_MODEL)),
                ('student_profile', models.ForeignKey(help_text='The StudentProfile associated with this snapshot.', on_delete=django.db.models.deletion.CASCADE, related_name='inventory_snapshots', to='profiles.studentprofile')),
            ],
            options={
                'verbose_name': 'student inventory snapshot',
                'verbose_name_plural': 'student inventory snapshots',
            },
        ),
        migrations.CreateModel(
            name='StudentInventoryStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('from_status', models.CharField(blank=True, max_length=50)),
                ('to_status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('REOPENED_FOR_CORRECTION', 'Reopened for Correction')], max_length=50)),
                ('transitioned_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('schema_key', models.CharField(blank=True, max_length=100)),
                ('schema_version', models.CharField(blank=True, max_length=50)),
                ('submission_sequence', models.PositiveIntegerField(blank=True, null=True)),
                ('is_baseline', models.BooleanField(default=False, help_text='Marks a legacy submitted payload captured before history was introduced.')),
                ('submitted_data_encrypted', apps.security.fields.EncryptedJSONField(blank=True, default=None, null=True)),
                ('reason_encrypted', apps.security.fields.EncryptedTextField(blank=True, default=None, max_plaintext_bytes=2048, null=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_status_history_entries', to=settings.AUTH_USER_MODEL)),
                ('snapshot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='status_history', to='inventory.studentinventorysnapshot')),
            ],
            options={
                'verbose_name': 'student inventory status history',
                'verbose_name_plural': 'student inventory status histories',
                'ordering': ['-transitioned_at', '-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='studentinventorysnapshot',
            constraint=models.UniqueConstraint(fields=('student_profile', 'academic_year'), name='unique_student_academic_year'),
        ),
        migrations.AddConstraint(
            model_name='studentinventorystatushistory',
            constraint=models.UniqueConstraint(condition=models.Q(('submission_sequence__isnull', False)), fields=('snapshot', 'submission_sequence'), name='unique_inventory_submission_history_sequence'),
        ),
        migrations.AddConstraint(
            model_name='studentinventorystatushistory',
            constraint=models.CheckConstraint(condition=models.Q(('from_status__in', ['', 'DRAFT', 'SUBMITTED', 'REOPENED_FOR_CORRECTION'])), name='inventory_history_from_status_known'),
        ),
    ]
