# Generated by Django 5.2.17 on 2026-09-07 14:06

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IdempotencyKey',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key_hash', models.CharField(db_index=True, max_length=64)),
                ('context_hash', models.CharField(db_index=True, help_text='Deterministic non-sensitive hash of actor/session context.', max_length=64)),
                ('session_key_hash', models.CharField(blank=True, db_index=True, help_text='Hashed session key for anonymous actions.', max_length=64, null=True)),
                ('action_scope', models.CharField(help_text='Identifies the workflow/action scope, e.g. good_moral.submit', max_length=100)),
                ('request_fingerprint', models.CharField(db_index=True, help_text='Deterministic hash of non-volatile request parameters.', max_length=64)),
                ('status', models.CharField(choices=[('processing', 'Processing'), ('succeeded', 'Succeeded'), ('failed', 'Failed'), ('expired', 'Expired')], db_index=True, default='processing', max_length=20)),
                ('related_object_type', models.CharField(blank=True, help_text='Type of the object created/modified by this action.', max_length=100, null=True)),
                ('related_object_id', models.CharField(blank=True, help_text='ID of the object created/modified by this action.', max_length=255, null=True)),
                ('safe_response_path', models.TextField(blank=True, help_text='A safe URL or redirect path representing the completed result.', null=True)),
                ('error_code', models.CharField(blank=True, help_text='Safe error code if the action failed.', max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('last_seen_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('metadata_json', models.JSONField(blank=True, default=dict, help_text='Safe, allowlisted audit metadata only.')),
                ('actor_user', models.ForeignKey(blank=True, help_text='The authenticated user who initiated the action.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='idempotency_keys', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OutboxEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_key', models.CharField(help_text='Unique, deterministic key to prevent duplicate enqueuing.', max_length=255, unique=True)),
                ('event_type', models.CharField(db_index=True, help_text='Stable event identifier, e.g. good_moral.request_created', max_length=100)),
                ('payload_json', models.JSONField(default=dict, help_text='Privacy-safe, allowlisted payload metadata only.')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('sent', 'Sent'), ('failed', 'Failed'), ('dead', 'Dead'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=20)),
                ('attempts', models.IntegerField(default=0)),
                ('max_attempts', models.IntegerField(default=5)),
                ('next_retry_at', models.DateTimeField(db_index=True)),
                ('locked_by', models.CharField(blank=True, max_length=255, null=True)),
                ('locked_at', models.DateTimeField(blank=True, null=True)),
                ('related_object_type', models.CharField(blank=True, max_length=100, null=True)),
                ('related_object_id', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('available_at', models.DateTimeField(db_index=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('last_error_code', models.CharField(blank=True, max_length=100, null=True)),
                ('last_error_safe_summary', models.TextField(blank=True, null=True)),
                ('idempotency_key', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='outbox_events', to='workflow.idempotencykey')),
            ],
        ),
        migrations.AddIndex(
            model_name='idempotencykey',
            index=models.Index(fields=['created_at'], name='workflow_id_created_83936a_idx'),
        ),
        migrations.AddIndex(
            model_name='idempotencykey',
            index=models.Index(fields=['expires_at', 'status'], name='workflow_id_expires_c25f36_idx'),
        ),
        migrations.AddConstraint(
            model_name='idempotencykey',
            constraint=models.UniqueConstraint(fields=('context_hash', 'action_scope', 'key_hash'), name='uniq_idempotency_context_scope_key'),
        ),
        migrations.AddIndex(
            model_name='outboxevent',
            index=models.Index(fields=['status', 'available_at'], name='workflow_ou_status_86f93d_idx'),
        ),
        migrations.AddIndex(
            model_name='outboxevent',
            index=models.Index(fields=['created_at'], name='workflow_ou_created_4edfc5_idx'),
        ),
    ]
