# Generated by Django 5.2.17 on 2026-09-07 14:06

import apps.support_needs.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
        ('profiles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SupportNeedType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.SlugField(help_text='Unique lowercase stable identifier.', max_length=100, unique=True, verbose_name='stable key')),
                ('label', models.CharField(help_text='Human-readable label for the support need type.', max_length=200, verbose_name='display label')),
                ('category', models.CharField(choices=[('household_support', 'Household Support'), ('disability_support', 'Disability Support'), ('family_context', 'Family Context'), ('employment_context', 'Employment Context'), ('financial_context', 'Financial Context'), ('living_condition', 'Living Condition'), ('educational_support', 'Educational Support'), ('office_approved_other', 'Office Approved Other')], help_text='Controlled category for grouping.', max_length=50, verbose_name='category')),
                ('sensitivity_level', models.CharField(choices=[('internal', 'Internal'), ('protected', 'Protected'), ('confidential', 'Confidential')], default='internal', max_length=50, verbose_name='sensitivity level')),
                ('requires_verification', models.BooleanField(default=True, help_text='If true, a counselor or staff must verify the record before it becomes official.', verbose_name='requires verification')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this support need type is currently active.', verbose_name='is active')),
                ('source_notes', models.TextField(blank=True, help_text='Safe governance notes regarding the support need definition/standards only.', verbose_name='source notes')),
            ],
            options={
                'verbose_name': 'support need type',
                'verbose_name_plural': 'support need types',
                'indexes': [models.Index(fields=['category'], name='support_nee_categor_bdc5f0_idx'), models.Index(fields=['is_active'], name='support_nee_is_acti_0808c9_idx'), models.Index(fields=['requires_verification'], name='support_nee_require_acad9f_idx')],
            },
        ),
        migrations.CreateModel(
            name='StudentSupportNeed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('draft', 'Candidate'), ('active', 'Active'), ('needs_review', 'Needs Review'), ('verified', 'Verified'), ('disputed', 'Disputed'), ('inactive', 'Inactive'), ('archived', 'Archived')], default='draft', max_length=50, verbose_name='status')),
                ('source_type', models.CharField(choices=[('individual_inventory', 'Individual Inventory'), ('student_provided', 'Student Provided'), ('counselor_staff_verification', 'Counselor/Staff Verification'), ('official_document_presented', 'Official Document Presented'), ('manual_office_validation', 'Manual Office Validation'), ('imported_official_list_future', 'Imported Official List (Future)')], max_length=50, verbose_name='source type')),
                ('source_app_label', models.CharField(blank=True, max_length=100, null=True, verbose_name='source app label')),
                ('source_model_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='source model name')),
                ('source_object_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='source object ID')),
                ('source_snapshot_label', models.CharField(blank=True, help_text='Safe label such as academic year, schema version.', max_length=100, null=True, verbose_name='source snapshot label')),
                ('source_mapping_version', models.CharField(blank=True, help_text='Version of the bounded source mapping used for derivation.', max_length=50, null=True, verbose_name='source mapping version')),
                ('evidence_summary_json', models.JSONField(blank=True, help_text='Safe structured evidence metadata. No raw narrative/PII.', null=True, validators=[apps.support_needs.models.validate_support_evidence_summary], verbose_name='evidence summary json')),
                ('verified_at', models.DateTimeField(blank=True, null=True, verbose_name='verified at')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='reviewed at')),
                ('effective_from', models.DateField(blank=True, null=True, verbose_name='effective from')),
                ('effective_until', models.DateField(blank=True, null=True, verbose_name='effective until')),
                ('review_due_at', models.DateTimeField(blank=True, null=True, verbose_name='review due at')),
                ('archived_at', models.DateTimeField(blank=True, null=True, verbose_name='archived at')),
                ('disputed_at', models.DateTimeField(blank=True, null=True, verbose_name='disputed at')),
                ('metadata_json', models.JSONField(blank=True, null=True, validators=[apps.support_needs.models.validate_support_metadata], verbose_name='metadata json')),
                ('archived_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='archived_support_needs', to=settings.AUTH_USER_MODEL)),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_support_needs', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_support_needs', to=settings.AUTH_USER_MODEL)),
                ('source_inventory_snapshot', models.ForeignKey(blank=True, help_text='Protected provenance for an Inventory-derived record.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='support_needs', to='inventory.studentinventorysnapshot')),
                ('source_submission_history', models.ForeignKey(blank=True, help_text='Protected immutable submission provenance.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='support_needs', to='inventory.studentinventorystatushistory')),
                ('student_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='support_needs', to='profiles.studentprofile')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_support_needs', to=settings.AUTH_USER_MODEL)),
                ('support_need_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_support_needs', to='support_needs.supportneedtype')),
            ],
            options={
                'verbose_name': 'student support need',
                'verbose_name_plural': 'student support needs',
                'indexes': [models.Index(fields=['student_profile'], name='support_nee_student_3e4f5f_idx'), models.Index(fields=['support_need_type'], name='support_nee_support_36ccfe_idx'), models.Index(fields=['status'], name='support_nee_status_ee3b12_idx'), models.Index(fields=['source_type'], name='support_nee_source__8e8d9f_idx'), models.Index(fields=['effective_from'], name='support_nee_effecti_e2f308_idx'), models.Index(fields=['effective_until'], name='support_nee_effecti_19510b_idx'), models.Index(fields=['review_due_at'], name='support_nee_review__5c84c5_idx'), models.Index(fields=['source_inventory_snapshot', 'support_need_type'], name='support_nee_source__a5ef17_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('source_inventory_snapshot__isnull', False)), fields=('source_inventory_snapshot', 'support_need_type'), name='unique_inventory_support_need_per_snapshot_type'), models.UniqueConstraint(condition=models.Q(('source_inventory_snapshot__isnull', True), ('status__in', ['draft', 'active', 'needs_review', 'verified'])), fields=('student_profile', 'support_need_type'), name='unique_manual_active_support_need_per_student_type')],
            },
        ),
    ]
