# Generated by Django 5.2.17 on 2026-09-07 14:06

import apps.security.fields
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appointments', '0001_initial'),
        ('referrals', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CallSlip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reference_code', models.CharField(editable=False, max_length=25, unique=True)),
                ('reissue_reason_code', models.CharField(blank=True, choices=[('AFTER_NO_SHOW', 'Follow-up after no-show'), ('AFTER_EXPIRY', 'Replacement after expiry'), ('AFTER_CANCELLATION', 'Replacement after cancellation')], max_length=30)),
                ('source_type', models.CharField(choices=[('OFFICE_INITIATED', 'Office Initiated'), ('REFERRAL', 'Referral'), ('APPOINTMENT', 'Appointment'), ('COUNSELOR_FOLLOW_UP', 'Counselor Follow-up'), ('OTHER_APPROVED', 'Other Approved')], max_length=30)),
                ('purpose_code', models.CharField(choices=[('ROUTINE_INTERVIEW_REPORTING', 'Routine Interview Reporting'), ('COUNSELOR_FOLLOW_UP', 'Counselor Follow-up'), ('GUIDANCE_INTERVIEW', 'Guidance Interview'), ('APPOINTMENT_REPORTING', 'Appointment Reporting'), ('GENERAL_OFFICE_REPORTING', 'General Office Reporting'), ('DOCUMENT_FOLLOW_UP', 'Document Follow-up'), ('OTHER_APPROVED', 'Other Approved')], max_length=30)),
                ('destination_code', models.CharField(choices=[('GUIDANCE_OFFICE', 'Guidance Office'), ('ASSIGNED_COUNSELOR', 'Assigned Counselor'), ('APPROVED_OFFICE_LOCATION', 'Approved Office Location'), ('AUTHENTICATED_ONLINE_ARRANGEMENT', 'Authenticated Online Arrangement')], max_length=50)),
                ('report_to_destination', models.CharField(max_length=255)),
                ('scheduled_start_at', models.DateTimeField(blank=True, null=True)),
                ('scheduled_end_at', models.DateTimeField(blank=True, null=True)),
                ('expected_duration_minutes', models.PositiveIntegerField(default=60)),
                ('mode', models.CharField(choices=[('ONSITE', 'On-site'), ('ONLINE', 'Online')], default='ONSITE', max_length=10)),
                ('student_safe_location', models.CharField(blank=True, max_length=255)),
                ('student_safe_instructions', models.TextField(blank=True)),
                ('student_safe_instructions_encrypted', apps.security.fields.EncryptedTextField(blank=True, default=None, null=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('ISSUED', 'Issued'), ('ACKNOWLEDGED', 'Acknowledged'), ('RESCHEDULE_REQUESTED', 'Reschedule Requested'), ('ATTENDED', 'Attended'), ('NO_SHOW', 'No Show'), ('EXPIRED', 'Expired'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=30)),
                ('course_snapshot', models.CharField(blank=True, max_length=100)),
                ('year_level_snapshot', models.CharField(blank=True, max_length=30)),
                ('office_only_remarks', models.TextField(blank=True)),
                ('office_only_remarks_encrypted', apps.security.fields.EncryptedTextField(blank=True, default=None, null=True)),
                ('cancel_reason_code', models.CharField(blank=True, choices=[('WORKFLOW_PROGRESSION', 'Workflow Progression'), ('SCHEDULE_CHANGE', 'Schedule Change'), ('ASSIGNMENT_CHANGE', 'Assignment Change'), ('STUDENT_REQUEST_APPROVED', 'Student Request Approved'), ('STUDENT_REQUEST_DECLINED', 'Student Request Declined'), ('DUPLICATE', 'Duplicate Record'), ('INVALID_NOTICE', 'Invalid Notice'), ('WRONG_STUDENT', 'Wrong Student'), ('OFFICE_CLOSURE', 'Office Closure'), ('COUNSELOR_UNAVAILABLE', 'Counselor Unavailable'), ('STUDENT_UNAVAILABLE', 'Student Unavailable'), ('NO_RESPONSE', 'No Response'), ('OTHER_STRUCTURED', 'Other Structured Reason')], max_length=50)),
                ('cancellation_detail', models.TextField(blank=True)),
                ('cancellation_detail_encrypted', apps.security.fields.EncryptedTextField(blank=True, default=None, null=True)),
                ('expiry_reason_code', models.CharField(blank=True, choices=[('WORKFLOW_PROGRESSION', 'Workflow Progression'), ('SCHEDULE_CHANGE', 'Schedule Change'), ('ASSIGNMENT_CHANGE', 'Assignment Change'), ('STUDENT_REQUEST_APPROVED', 'Student Request Approved'), ('STUDENT_REQUEST_DECLINED', 'Student Request Declined'), ('DUPLICATE', 'Duplicate Record'), ('INVALID_NOTICE', 'Invalid Notice'), ('WRONG_STUDENT', 'Wrong Student'), ('OFFICE_CLOSURE', 'Office Closure'), ('COUNSELOR_UNAVAILABLE', 'Counselor Unavailable'), ('STUDENT_UNAVAILABLE', 'Student Unavailable'), ('NO_RESPONSE', 'No Response'), ('OTHER_STRUCTURED', 'Other Structured Reason')], max_length=50)),
                ('no_show_reason_code', models.CharField(blank=True, choices=[('WORKFLOW_PROGRESSION', 'Workflow Progression'), ('SCHEDULE_CHANGE', 'Schedule Change'), ('ASSIGNMENT_CHANGE', 'Assignment Change'), ('STUDENT_REQUEST_APPROVED', 'Student Request Approved'), ('STUDENT_REQUEST_DECLINED', 'Student Request Declined'), ('DUPLICATE', 'Duplicate Record'), ('INVALID_NOTICE', 'Invalid Notice'), ('WRONG_STUDENT', 'Wrong Student'), ('OFFICE_CLOSURE', 'Office Closure'), ('COUNSELOR_UNAVAILABLE', 'Counselor Unavailable'), ('STUDENT_UNAVAILABLE', 'Student Unavailable'), ('NO_RESPONSE', 'No Response'), ('OTHER_STRUCTURED', 'Other Structured Reason')], max_length=50)),
                ('no_show_detail', models.TextField(blank=True)),
                ('no_show_detail_encrypted', apps.security.fields.EncryptedTextField(blank=True, default=None, null=True)),
                ('issued_at', models.DateTimeField(blank=True, null=True)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('reported_at', models.DateTimeField(blank=True, null=True)),
                ('attendance_recorded_at', models.DateTimeField(blank=True, null=True)),
                ('interview_ended_at', models.DateTimeField(blank=True, null=True)),
                ('no_show_at', models.DateTimeField(blank=True, null=True)),
                ('expired_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('source_form_code', models.CharField(default='CNSC-OP-GTA-01F8', editable=False, max_length=50)),
                ('source_form_revision', models.PositiveIntegerField(default=0, editable=False)),
                ('source_form_family', models.CharField(default='call_slip', editable=False, max_length=50)),
                ('internal_schema_version', models.PositiveIntegerField(default=1)),
                ('creation_request_key', models.CharField(editable=False, max_length=100, unique=True)),
                ('acknowledged_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='call_slips_acknowledged', to=settings.AUTH_USER_MODEL)),
                ('appointment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='call_slips', to='appointments.appointment')),
                ('assigned_counselor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assigned_call_slips', to=settings.AUTH_USER_MODEL)),
                ('attendance_recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='call_slips_attendance_recorded', to=settings.AUTH_USER_MODEL)),
                ('cancelled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='call_slips_cancelled', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='call_slips_created', to=settings.AUTH_USER_MODEL)),
                ('expired_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='call_slips_expired', to=settings.AUTH_USER_MODEL)),
                ('issued_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='call_slips_issued', to=settings.AUTH_USER_MODEL)),
                ('no_show_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='call_slips_no_shown', to=settings.AUTH_USER_MODEL)),
                ('referral', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='call_slips', to='referrals.referral')),
                ('reissued_from', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reissued_as', to='call_slips.callslip')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='call_slips', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='call_slips_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='CallSlipAssignmentHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reason_code', models.CharField(choices=[('WORKFLOW_PROGRESSION', 'Workflow Progression'), ('SCHEDULE_CHANGE', 'Schedule Change'), ('ASSIGNMENT_CHANGE', 'Assignment Change'), ('STUDENT_REQUEST_APPROVED', 'Student Request Approved'), ('STUDENT_REQUEST_DECLINED', 'Student Request Declined'), ('DUPLICATE', 'Duplicate Record'), ('INVALID_NOTICE', 'Invalid Notice'), ('WRONG_STUDENT', 'Wrong Student'), ('OFFICE_CLOSURE', 'Office Closure'), ('COUNSELOR_UNAVAILABLE', 'Counselor Unavailable'), ('STUDENT_UNAVAILABLE', 'Student Unavailable'), ('NO_RESPONSE', 'No Response'), ('OTHER_STRUCTURED', 'Other Structured Reason')], max_length=50)),
                ('change_type', models.CharField(choices=[('INITIAL_ASSIGNMENT', 'Initial Assignment'), ('REASSIGNMENT', 'Reassignment')], max_length=30)),
                ('changed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('detail', models.TextField(blank=True)),
                ('detail_encrypted', apps.security.fields.EncryptedTextField(blank=True, default=None, null=True)),
                ('call_slip', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignment_histories', to='call_slips.callslip')),
                ('changed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='call_slip_assignment_changes', to=settings.AUTH_USER_MODEL)),
                ('from_counselor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('to_counselor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-changed_at'],
            },
        ),
        migrations.CreateModel(
            name='CallSlipRescheduleRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('previous_status_snapshot', models.CharField(choices=[('DRAFT', 'Draft'), ('ISSUED', 'Issued'), ('ACKNOWLEDGED', 'Acknowledged'), ('RESCHEDULE_REQUESTED', 'Reschedule Requested'), ('ATTENDED', 'Attended'), ('NO_SHOW', 'No Show'), ('EXPIRED', 'Expired'), ('CANCELLED', 'Cancelled')], max_length=30)),
                ('previous_start_at', models.DateTimeField()),
                ('previous_end_at', models.DateTimeField()),
                ('previous_expected_duration_minutes', models.PositiveIntegerField()),
                ('proposed_start_at', models.DateTimeField()),
                ('proposed_end_at', models.DateTimeField()),
                ('proposed_expected_duration_minutes', models.PositiveIntegerField()),
                ('student_reason', models.TextField()),
                ('student_reason_encrypted', apps.security.fields.EncryptedTextField(blank=True, default=None, null=True)),
                ('request_key', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('DECLINED', 'Declined')], default='PENDING', max_length=20)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('decision_code', models.CharField(blank=True, choices=[('WORKFLOW_PROGRESSION', 'Workflow Progression'), ('SCHEDULE_CHANGE', 'Schedule Change'), ('ASSIGNMENT_CHANGE', 'Assignment Change'), ('STUDENT_REQUEST_APPROVED', 'Student Request Approved'), ('STUDENT_REQUEST_DECLINED', 'Student Request Declined'), ('DUPLICATE', 'Duplicate Record'), ('INVALID_NOTICE', 'Invalid Notice'), ('WRONG_STUDENT', 'Wrong Student'), ('OFFICE_CLOSURE', 'Office Closure'), ('COUNSELOR_UNAVAILABLE', 'Counselor Unavailable'), ('STUDENT_UNAVAILABLE', 'Student Unavailable'), ('NO_RESPONSE', 'No Response'), ('OTHER_STRUCTURED', 'Other Structured Reason')], max_length=50)),
                ('decision_detail', models.TextField(blank=True)),
                ('decision_detail_encrypted', apps.security.fields.EncryptedTextField(blank=True, default=None, null=True)),
                ('call_slip', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reschedule_requests', to='call_slips.callslip')),
                ('decider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='call_slip_reschedule_decisions', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='call_slip_reschedule_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CallSlipScheduleHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('change_type', models.CharField(choices=[('INITIAL_ISSUE', 'Initial Issue'), ('REISSUE', 'Reissue'), ('RESCHEDULE_APPROVED', 'Reschedule Approved'), ('ASSIGNMENT_REEVALUATION', 'Assignment Reevaluation'), ('CANCELLATION', 'Cancellation')], max_length=30)),
                ('previous_start_at', models.DateTimeField(blank=True, null=True)),
                ('previous_end_at', models.DateTimeField(blank=True, null=True)),
                ('previous_expected_duration_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('new_start_at', models.DateTimeField(blank=True, null=True)),
                ('new_end_at', models.DateTimeField(blank=True, null=True)),
                ('new_expected_duration_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('reason_code', models.CharField(choices=[('WORKFLOW_PROGRESSION', 'Workflow Progression'), ('SCHEDULE_CHANGE', 'Schedule Change'), ('ASSIGNMENT_CHANGE', 'Assignment Change'), ('STUDENT_REQUEST_APPROVED', 'Student Request Approved'), ('STUDENT_REQUEST_DECLINED', 'Student Request Declined'), ('DUPLICATE', 'Duplicate Record'), ('INVALID_NOTICE', 'Invalid Notice'), ('WRONG_STUDENT', 'Wrong Student'), ('OFFICE_CLOSURE', 'Office Closure'), ('COUNSELOR_UNAVAILABLE', 'Counselor Unavailable'), ('STUDENT_UNAVAILABLE', 'Student Unavailable'), ('NO_RESPONSE', 'No Response'), ('OTHER_STRUCTURED', 'Other Structured Reason')], max_length=50)),
                ('changed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('availability_blocking_before', models.BooleanField(default=False)),
                ('availability_blocking_after', models.BooleanField(default=False)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='call_slip_schedule_changes', to=settings.AUTH_USER_MODEL)),
                ('call_slip', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='schedule_histories', to='call_slips.callslip')),
                ('new_counselor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('previous_counselor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-changed_at'],
            },
        ),
        migrations.CreateModel(
            name='CallSlipStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('from_status', models.CharField(blank=True, max_length=30)),
                ('to_status', models.CharField(choices=[('DRAFT', 'Draft'), ('ISSUED', 'Issued'), ('ACKNOWLEDGED', 'Acknowledged'), ('RESCHEDULE_REQUESTED', 'Reschedule Requested'), ('ATTENDED', 'Attended'), ('NO_SHOW', 'No Show'), ('EXPIRED', 'Expired'), ('CANCELLED', 'Cancelled')], max_length=30)),
                ('reason_code', models.CharField(choices=[('WORKFLOW_PROGRESSION', 'Workflow Progression'), ('SCHEDULE_CHANGE', 'Schedule Change'), ('ASSIGNMENT_CHANGE', 'Assignment Change'), ('STUDENT_REQUEST_APPROVED', 'Student Request Approved'), ('STUDENT_REQUEST_DECLINED', 'Student Request Declined'), ('DUPLICATE', 'Duplicate Record'), ('INVALID_NOTICE', 'Invalid Notice'), ('WRONG_STUDENT', 'Wrong Student'), ('OFFICE_CLOSURE', 'Office Closure'), ('COUNSELOR_UNAVAILABLE', 'Counselor Unavailable'), ('STUDENT_UNAVAILABLE', 'Student Unavailable'), ('NO_RESPONSE', 'No Response'), ('OTHER_STRUCTURED', 'Other Structured Reason')], max_length=50)),
                ('transitioned_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('request_key', models.CharField(blank=True, max_length=100)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='call_slip_status_changes', to=settings.AUTH_USER_MODEL)),
                ('call_slip', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='status_histories', to='call_slips.callslip')),
            ],
            options={
                'ordering': ['-transitioned_at'],
            },
        ),
        migrations.AddIndex(
            model_name='callslip',
            index=models.Index(fields=['status', 'scheduled_start_at'], name='call_slips__status_6627a3_idx'),
        ),
        migrations.AddIndex(
            model_name='callslip',
            index=models.Index(fields=['assigned_counselor', 'status', 'scheduled_start_at'], name='call_slips__assigne_62550e_idx'),
        ),
        migrations.AddIndex(
            model_name='callslip',
            index=models.Index(fields=['student', 'status'], name='call_slips__student_b2e2f1_idx'),
        ),
        migrations.AddIndex(
            model_name='callslip',
            index=models.Index(fields=['reference_code'], name='call_slips__referen_35a7d9_idx'),
        ),
        migrations.AddConstraint(
            model_name='callslip',
            constraint=models.UniqueConstraint(condition=models.Q(('referral__isnull', False), ('status__in', ['DRAFT', 'ISSUED', 'ACKNOWLEDGED', 'RESCHEDULE_REQUESTED'])), fields=('referral',), name='uniq_active_referral_call_slip'),
        ),
        migrations.AddConstraint(
            model_name='callslip',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('referral__isnull', False), ('source_type', 'REFERRAL')), models.Q(models.Q(('source_type', 'REFERRAL'), _negated=True), ('referral__isnull', True)), _connector='OR'), name='call_slip_referral_source_pair'),
        ),
        migrations.AddConstraint(
            model_name='callslip',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('reissue_reason_code', ''), ('reissued_from__isnull', True)), models.Q(('reissued_from__isnull', False), ('reissue_reason_code__in', ['AFTER_NO_SHOW', 'AFTER_EXPIRY', 'AFTER_CANCELLATION'])), _connector='OR'), name='call_slip_reissue_pair'),
        ),
        migrations.AddConstraint(
            model_name='callslipreschedulerequest',
            constraint=models.UniqueConstraint(fields=('call_slip', 'request_key'), name='uniq_call_slip_reschedule_request'),
        ),
        migrations.AddConstraint(
            model_name='callslipreschedulerequest',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'PENDING')), fields=('call_slip',), name='uniq_pending_call_slip_reschedule'),
        ),
    ]
