# Generated by Django 5.2.17 on 2026-09-07 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CounselorCoverage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('campus', models.CharField(blank=True, max_length=100, null=True)),
                ('college', models.CharField(blank=True, max_length=100, null=True)),
                ('department', models.CharField(blank=True, max_length=100, null=True)),
                ('program', models.CharField(blank=True, max_length=100, null=True)),
                ('is_primary', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('starts_at', models.DateField()),
                ('ends_at', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'counselor coverage',
                'verbose_name_plural': 'counselor coverages',
            },
        ),
        migrations.CreateModel(
            name='WorkflowAuthorityGrant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('capability', models.CharField(db_index=True, max_length=120)),
                ('scope_mode', models.CharField(choices=[('COUNSELOR_COVERAGE', 'Counselor coverage'), ('EXPLICIT_ORGANIZATION', 'Explicit organization'), ('ASSIGNED_RECORDS', 'Assigned records'), ('OFFICE_WIDE', 'Office-wide')], max_length=30)),
                ('campus', models.CharField(blank=True, max_length=100, null=True)),
                ('college', models.CharField(blank=True, max_length=100, null=True)),
                ('department', models.CharField(blank=True, max_length=100, null=True)),
                ('program', models.CharField(blank=True, max_length=100, null=True)),
                ('valid_from', models.DateField()),
                ('valid_until', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('REVOKED', 'Revoked')], db_index=True, default='ACTIVE', max_length=20)),
                ('grant_reason_code', models.CharField(choices=[('OFFICE_DELEGATION', 'Office delegation'), ('LOCAL_WORKFLOW', 'Local workflow'), ('TEMPORARY_COVERAGE', 'Temporary coverage'), ('ABSENCE_COVER', 'Absence cover'), ('ROLE_DUTY', 'Role duty'), ('MIGRATED_ASSIGNMENT', 'Migrated assignment')], max_length=40)),
                ('grant_reason_note', models.CharField(blank=True, max_length=500)),
                ('source_type', models.CharField(choices=[('MANUAL', 'Manual'), ('BULK', 'Bulk assignment'), ('MIGRATION', 'Legacy migration'), ('SYSTEM', 'System')], default='MANUAL', max_length=20)),
                ('source_reference', models.CharField(blank=True, max_length=120)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('revocation_reason_code', models.CharField(blank=True, choices=[('POLICY_CHANGE', 'Policy change'), ('ROLE_CHANGE', 'Role change'), ('ACCOUNT_DEACTIVATED', 'Account deactivated'), ('EXPIRED', 'Expired'), ('NO_LONGER_NEEDED', 'No longer needed'), ('SECURITY', 'Security')], max_length=40)),
            ],
            options={
                'verbose_name': 'workflow authority grant',
                'verbose_name_plural': 'workflow authority grants',
            },
        ),
    ]
