# Generated by Django 5.2.17 on 2026-09-07 14:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('access_control', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='counselorcoverage',
            name='assigned_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_coverages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='counselorcoverage',
            name='counselor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coverages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='workflowauthoritygrant',
            name='granted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='authority_grants_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='workflowauthoritygrant',
            name='grantee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='authority_grants', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='workflowauthoritygrant',
            name='revoked_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='authority_grants_revoked', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='workflowauthoritygrant',
            index=models.Index(fields=['grantee', 'capability', 'status'], name='access_cont_grantee_a47346_idx'),
        ),
        migrations.AddIndex(
            model_name='workflowauthoritygrant',
            index=models.Index(fields=['valid_from', 'valid_until'], name='access_cont_valid_f_606e48_idx'),
        ),
    ]
