# Generated by Django 5.2.17 on 2026-09-07 14:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLogEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor_role', models.CharField(blank=True, help_text="Snapshot of the user's role at the time of the action.", max_length=50)),
                ('action_type', models.CharField(help_text='e.g., STATUS_TRANSITION, SENSITIVE_VIEW', max_length=100)),
                ('event_category', models.CharField(help_text='e.g., SECURITY, DATA_ACCESS', max_length=100)),
                ('severity', models.CharField(default='INFO', help_text='e.g., INFO, WARNING, CRITICAL', max_length=20)),
                ('target_model', models.CharField(help_text='Name of the model affected, e.g., Appointment', max_length=100)),
                ('target_object_id', models.CharField(help_text='String representation of the object ID', max_length=255)),
                ('reference_code', models.CharField(blank=True, help_text='Immutable workflow reference code, e.g. APT-2026-0001', max_length=50, null=True)),
                ('actor_ip_hash', models.CharField(blank=True, help_text='Hashed IP address for privacy', max_length=64, null=True)),
                ('user_agent_hash', models.CharField(blank=True, help_text='Hashed User-Agent for privacy', max_length=64, null=True)),
                ('request_id', models.CharField(blank=True, help_text='Correlation ID for the HTTP request', max_length=100, null=True)),
                ('trace_id', models.CharField(blank=True, help_text='Correlation ID for distributed tracing/jobs', max_length=100, null=True)),
                ('source_app', models.CharField(blank=True, help_text='The Django app generating the log', max_length=100, null=True)),
                ('source_view', models.CharField(blank=True, help_text='The view or service function generating the log', max_length=255, null=True)),
                ('safe_metadata', models.JSONField(default=dict, help_text='Sanitized metadata. MUST NOT contain raw secrets or PII narratives.')),
                ('metadata_schema_version', models.IntegerField(default=1, help_text='Version of the metadata structure.')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When the event occurred.')),
                ('actor_user', models.ForeignKey(blank=True, help_text='User who performed the action. Null for system background tasks.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Audit Log Entry',
                'verbose_name_plural': 'Audit Log Entries',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['created_at'], name='audit_audit_created_3e5798_idx'), models.Index(fields=['actor_user'], name='audit_audit_actor_u_c3a92e_idx'), models.Index(fields=['action_type'], name='audit_audit_action__7307e1_idx'), models.Index(fields=['event_category'], name='audit_audit_event_c_44156a_idx'), models.Index(fields=['severity'], name='audit_audit_severit_f8d12c_idx'), models.Index(fields=['reference_code'], name='audit_audit_referen_544048_idx'), models.Index(fields=['target_model', 'target_object_id'], name='audit_audit_target__d99c08_idx')],
            },
        ),
    ]
