# Generated by Django 5.2.17 on 2026-09-07 14:06

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documents', '0001_initial'),
        ('inventory', '0001_initial'),
        ('profiles', '0001_initial'),
        ('security', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportDefinition',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key', models.CharField(db_index=True, help_text='Unique key identifier, e.g., exit_interview_completion_summary', max_length=100, unique=True, verbose_name='report key')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('family', models.CharField(choices=[('student_profile_inventory', 'Institutional Student Profiling & Inventory'), ('feedback_csm', 'Client Satisfaction Measurement (CSM) / Feedback'), ('exit_interview', 'Exit Interview Completion'), ('graduate_tracer', 'Graduate Tracer Survey'), ('form_collection_progress', 'Form Collection Progress'), ('document_requests', 'Good Moral & Document Requests'), ('appointments_counseling_workload', 'Appointments & Counseling Workload'), ('referrals_call_slips', 'Referrals & Call Slips'), ('public_contact', 'Public Contact / Suggestion Box'), ('workflow_notifications', 'Workflow & Notification Metrics'), ('audit_report_access', 'Audit & Report Access Logs')], db_index=True, max_length=50, verbose_name='report family')),
                ('sensitivity_level', models.CharField(choices=[('PUBLIC', 'Public (unrestricted internal/external view)'), ('INTERNAL', 'Internal (general guidance office view)'), ('SENSITIVE', 'Sensitive (restricted categories, suppressed cells)'), ('RESTRICTED', 'Restricted (elevated role + approval required)'), ('FORBIDDEN', 'Forbidden (never expose in reports/queries)')], default='SENSITIVE', max_length=30, verbose_name='sensitivity level')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='is active')),
                ('allowed_scope_metadata_json', models.JSONField(blank=True, default=dict, help_text='Governance scopes allowed to view/run this report', verbose_name='allowed scope metadata')),
                ('activated_at', models.DateTimeField(blank=True, null=True, verbose_name='activated at')),
                ('deactivated_at', models.DateTimeField(blank=True, null=True, verbose_name='deactivated at')),
                ('metadata_json', models.JSONField(blank=True, default=dict, verbose_name='metadata')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_report_definitions', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_report_definitions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'report definition',
                'verbose_name_plural': 'report definitions',
            },
        ),
        migrations.CreateModel(
            name='ReportRun',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('filter_hash', models.CharField(db_index=True, help_text='Deterministic HMAC-SHA256 hash of sanitized/redacted filters', max_length=64, verbose_name='filter hash')),
                ('filter_summary_json', models.JSONField(blank=True, default=dict, help_text='Redacted/safe filter summary (no PII or raw parameters)', verbose_name='filter summary JSON')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('RUNNING', 'Running'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], db_index=True, default='PENDING', max_length=30, verbose_name='status')),
                ('aggregate_count', models.IntegerField(blank=True, null=True, verbose_name='aggregate count')),
                ('cell_count', models.IntegerField(blank=True, null=True, verbose_name='cell count')),
                ('suppression_applied', models.BooleanField(default=False, verbose_name='suppression applied')),
                ('suppressed_cell_count', models.IntegerField(default=0, verbose_name='suppressed cell count')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='started at')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='completed at')),
                ('failed_at', models.DateTimeField(blank=True, null=True, verbose_name='failed at')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='expires at')),
                ('metadata_json', models.JSONField(blank=True, default=dict, verbose_name='metadata')),
                ('report_definition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='reports.reportdefinition')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='report_runs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'report run',
                'verbose_name_plural': 'report runs',
            },
        ),
        migrations.CreateModel(
            name='ReportExportRequest',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('export_type', models.CharField(choices=[('aggregate', 'Aggregate'), ('sensitive_aggregate', 'Sensitive Aggregate'), ('identifiable', 'Identifiable'), ('administrative_operational', 'Administrative/Operational'), ('official_template', 'Official Template'), ('denied_deferred', 'Denied/Deferred')], default='aggregate', max_length=50, verbose_name='export type')),
                ('export_format', models.CharField(choices=[('csv', 'CSV'), ('pdf', 'PDF'), ('deferred_excel', 'Deferred Excel'), ('deferred_pdf', 'Deferred PDF'), ('deferred_docx', 'Deferred DOCX'), ('html_preview', 'HTML Preview')], default='csv', max_length=50, verbose_name='export format')),
                ('status', models.CharField(choices=[('requested', 'Requested'), ('pending_approval', 'Pending Approval'), ('approved', 'Approved'), ('denied', 'Denied'), ('generating', 'Generating'), ('generated', 'Generated'), ('generation_failed', 'Generation Failed'), ('downloaded', 'Downloaded'), ('expired', 'Expired'), ('cancelled', 'Cancelled'), ('archived', 'Archived')], db_index=True, default='requested', max_length=50, verbose_name='status')),
                ('scope_summary_json', models.JSONField(blank=True, default=dict, verbose_name='scope summary JSON')),
                ('filter_hash', models.CharField(db_index=True, max_length=64, verbose_name='filter hash')),
                ('filter_summary_json', models.JSONField(blank=True, default=dict, verbose_name='filter summary JSON')),
                ('includes_identifiable_data', models.BooleanField(default=False, verbose_name='includes identifiable data')),
                ('includes_sensitive_data', models.BooleanField(default=False, verbose_name='includes sensitive data')),
                ('purpose', models.CharField(blank=True, max_length=500, verbose_name='purpose')),
                ('approval_reason', models.CharField(blank=True, max_length=500, verbose_name='approval reason')),
                ('denial_reason', models.CharField(blank=True, max_length=500, verbose_name='denial reason')),
                ('suppression_applied', models.BooleanField(default=False, verbose_name='suppression applied')),
                ('suppressed_cell_count', models.IntegerField(default=0, verbose_name='suppressed cell count')),
                ('generation_metadata_json', models.JSONField(blank=True, default=dict, verbose_name='generation metadata JSON')),
                ('requested_at', models.DateTimeField(auto_now_add=True, verbose_name='requested at')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='approved at')),
                ('denied_at', models.DateTimeField(blank=True, null=True, verbose_name='denied at')),
                ('generation_started_at', models.DateTimeField(blank=True, null=True, verbose_name='generation started at')),
                ('generated_at', models.DateTimeField(blank=True, null=True, verbose_name='generated at')),
                ('downloaded_at', models.DateTimeField(blank=True, null=True, verbose_name='downloaded at')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='expires at')),
                ('expired_at', models.DateTimeField(blank=True, null=True, verbose_name='expired at')),
                ('cancelled_at', models.DateTimeField(blank=True, null=True, verbose_name='cancelled at')),
                ('archived_at', models.DateTimeField(blank=True, null=True, verbose_name='archived at')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='report_export_requests_approved', to=settings.AUTH_USER_MODEL)),
                ('denied_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='report_export_requests_denied', to=settings.AUTH_USER_MODEL)),
                ('document_template_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='export_requests', to='documents.documenttemplateversion')),
                ('generated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='report_export_requests_generated', to=settings.AUTH_USER_MODEL)),
                ('generated_document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='export_requests', to='documents.generateddocument')),
                ('protected_file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='export_requests', to='security.protectedfile')),
                ('report_definition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='export_requests', to='reports.reportdefinition')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='report_export_requests_requested', to=settings.AUTH_USER_MODEL)),
                ('report_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='export_requests', to='reports.reportrun')),
            ],
            options={
                'verbose_name': 'report export request',
                'verbose_name_plural': 'report export requests',
            },
        ),
        migrations.CreateModel(
            name='StudentProfilingFact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_schema_key', models.CharField(max_length=100)),
                ('source_schema_version', models.CharField(max_length=50)),
                ('mapping_version', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('READY', 'Ready'), ('UNREADABLE', 'Unreadable confidential source'), ('INVALID', 'Invalid profiling source'), ('REOPENED', 'Reopened for correction')], db_index=True, default='READY', max_length=20)),
                ('data_quality_code', models.CharField(blank=True, max_length=80)),
                ('gender_code', models.CharField(blank=True, max_length=60)),
                ('age_band_code', models.CharField(blank=True, max_length=60)),
                ('civil_status_code', models.CharField(blank=True, max_length=60)),
                ('physical_disability_code', models.CharField(blank=True, max_length=60)),
                ('religion_code', models.CharField(blank=True, max_length=80)),
                ('mother_living_status_code', models.CharField(blank=True, max_length=60)),
                ('father_living_status_code', models.CharField(blank=True, max_length=60)),
                ('parents_marital_status_code', models.CharField(blank=True, max_length=80)),
                ('municipality_code', models.CharField(blank=True, max_length=100)),
                ('parents_annual_income_code', models.CharField(blank=True, max_length=60)),
                ('mother_occupation_code', models.CharField(blank=True, max_length=60)),
                ('father_occupation_code', models.CharField(blank=True, max_length=60)),
                ('living_condition_code', models.CharField(blank=True, max_length=60)),
                ('cohort', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profiling_facts', to='profiles.studentacademiccohort')),
                ('inventory_snapshot', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profiling_fact', to='inventory.studentinventorysnapshot')),
            ],
            options={
                'verbose_name': 'student profiling fact',
                'verbose_name_plural': 'student profiling facts',
            },
        ),
        migrations.AddIndex(
            model_name='reportdefinition',
            index=models.Index(fields=['key'], name='reports_rep_key_760a18_idx'),
        ),
        migrations.AddIndex(
            model_name='reportdefinition',
            index=models.Index(fields=['family'], name='reports_rep_family_3d2c51_idx'),
        ),
        migrations.AddIndex(
            model_name='reportdefinition',
            index=models.Index(fields=['is_active'], name='reports_rep_is_acti_f2fb13_idx'),
        ),
        migrations.AddIndex(
            model_name='reportrun',
            index=models.Index(fields=['status'], name='reports_rep_status_f320b8_idx'),
        ),
        migrations.AddIndex(
            model_name='reportrun',
            index=models.Index(fields=['requested_by'], name='reports_rep_request_b46438_idx'),
        ),
        migrations.AddIndex(
            model_name='reportrun',
            index=models.Index(fields=['filter_hash'], name='reports_rep_filter__6cf9ce_idx'),
        ),
        migrations.AddIndex(
            model_name='reportrun',
            index=models.Index(fields=['created_at'], name='reports_rep_created_cbe32c_idx'),
        ),
        migrations.AddIndex(
            model_name='reportexportrequest',
            index=models.Index(fields=['status'], name='reports_rep_status_fc93ae_idx'),
        ),
        migrations.AddIndex(
            model_name='reportexportrequest',
            index=models.Index(fields=['requested_by'], name='reports_rep_request_88ba19_idx'),
        ),
        migrations.AddIndex(
            model_name='reportexportrequest',
            index=models.Index(fields=['report_definition'], name='reports_rep_report__ab62a5_idx'),
        ),
        migrations.AddIndex(
            model_name='reportexportrequest',
            index=models.Index(fields=['report_run'], name='reports_rep_report__b201cd_idx'),
        ),
        migrations.AddIndex(
            model_name='reportexportrequest',
            index=models.Index(fields=['export_type'], name='reports_rep_export__d3bfc7_idx'),
        ),
        migrations.AddIndex(
            model_name='reportexportrequest',
            index=models.Index(fields=['export_format'], name='reports_rep_export__38f05a_idx'),
        ),
        migrations.AddIndex(
            model_name='reportexportrequest',
            index=models.Index(fields=['expires_at'], name='reports_rep_expires_fefe95_idx'),
        ),
        migrations.AddIndex(
            model_name='reportexportrequest',
            index=models.Index(fields=['requested_at'], name='reports_rep_request_8e8368_idx'),
        ),
        migrations.AddIndex(
            model_name='reportexportrequest',
            index=models.Index(fields=['filter_hash'], name='reports_rep_filter__4badce_idx'),
        ),
        migrations.AddIndex(
            model_name='studentprofilingfact',
            index=models.Index(fields=['cohort', 'status'], name='reports_stu_cohort__929167_idx'),
        ),
        migrations.AddIndex(
            model_name='studentprofilingfact',
            index=models.Index(fields=['mapping_version', 'status'], name='reports_stu_mapping_d59e73_idx'),
        ),
    ]
