# Generated by Django 5.2.17 on 2026-09-07 14:06

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentActivationInvitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('token_hash', models.CharField(db_index=True, help_text='HMAC-SHA256 hex digest of the raw activation token.', max_length=64, unique=True, verbose_name='token hash')),
                ('token_version', models.CharField(default='account-activation-student-v1', max_length=40)),
                ('token_reference', models.UUIDField(db_index=True, default=uuid.uuid4, help_text='Opaque invitation reference used to reconstruct the signed token at send time.', unique=True)),
                ('delivery_email_hash', models.CharField(default='', max_length=64)),
                ('expires_at', models.DateTimeField(help_text='The date and time when the invitation expires.', verbose_name='expires at')),
                ('used_at', models.DateTimeField(blank=True, help_text='Timestamp when the token was successfully used.', null=True, verbose_name='used at')),
                ('revoked_at', models.DateTimeField(blank=True, help_text='Timestamp when the token was manually or programmatically revoked.', null=True, verbose_name='revoked at')),
                ('revocation_reason', models.CharField(blank=True, default='', max_length=80)),
                ('created_by', models.ForeignKey(blank=True, help_text='The user who issued or reissued this invitation.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_invitations', to=settings.AUTH_USER_MODEL)),
                ('reissued_from', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reissues', to='student_activation.studentactivationinvitation')),
                ('revoked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revoked_student_activation_invitations', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(help_text='The inactive STUDENT user account associated with this token.', on_delete=django.db.models.deletion.CASCADE, related_name='activation_invitations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'student activation invitation',
                'verbose_name_plural': 'student activation invitations',
            },
        ),
    ]
