# Generated by Django 5.2.17 on 2026-09-07 14:06

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduleCoordinationLock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('scope_key', models.CharField(max_length=120, unique=True)),
            ],
            options={
                'verbose_name': 'schedule coordination lock',
                'verbose_name_plural': 'schedule coordination locks',
            },
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reference_code', models.CharField(editable=False, help_text='Immutable AY-based reference code (e.g. APT-AY2526-000001).', max_length=25, unique=True)),
                ('appointment_type', models.CharField(choices=[('COUNSELING', 'Counseling'), ('ROUTINE_INTERVIEW', 'Routine Interview'), ('FOLLOW_UP', 'Follow-up'), ('OTHER', 'Other')], help_text='Type of appointment requested.', max_length=30)),
                ('appointment_mode', models.CharField(choices=[('ONSITE', 'On-site'), ('ONLINE', 'Online')], help_text='Delivery mode: on-site or online.', max_length=10)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('PENDING_REVIEW', 'Pending Review'), ('APPROVED', 'Approved'), ('SCHEDULED', 'Scheduled'), ('DECLINED', 'Declined'), ('CANCELLED_BY_STUDENT', 'Cancelled by Student'), ('CANCELLED_BY_OFFICE', 'Cancelled by Office'), ('LATE_CANCELLATION_REQUESTED', 'Late Cancellation Requested'), ('LATE_CANCELLATION_APPROVED', 'Late Cancellation Approved'), ('LATE_CANCELLATION_DECLINED', 'Late Cancellation Declined'), ('COMPLETED', 'Completed'), ('NO_SHOW', 'No Show')], default='DRAFT', help_text='Current appointment status.', max_length=40)),
                ('reason', models.TextField(blank=True, help_text='Student-provided reason for the appointment.')),
                ('requested_date', models.DateField(blank=True, help_text="Student's preferred date.", null=True)),
                ('requested_start_time', models.TimeField(blank=True, help_text="Student's preferred start time.", null=True)),
                ('confirmed_date', models.DateField(blank=True, help_text='Office-confirmed date.', null=True)),
                ('confirmed_start_time', models.TimeField(blank=True, help_text='Office-confirmed start time.', null=True)),
                ('confirmed_end_time', models.TimeField(blank=True, help_text='Office-confirmed end time (default: start + slot duration).', null=True)),
                ('actual_start_time', models.DateTimeField(blank=True, help_text='Actual session start timestamp.', null=True)),
                ('actual_end_time', models.DateTimeField(blank=True, help_text='Actual session end timestamp.', null=True)),
                ('cancellation_reason', models.TextField(blank=True, help_text='Reason if cancelled.')),
                ('decline_reason', models.TextField(blank=True, help_text='Reason if declined by office. Not visible to student in raw form.')),
                ('internal_notes', models.TextField(blank=True, help_text='Staff/counselor-only notes. Never rendered in student templates.')),
                ('submitted_at', models.DateTimeField(blank=True, help_text='Timestamp when the appointment was submitted.', null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, help_text='Timestamp when the appointment was reviewed.', null=True)),
                ('completed_at', models.DateTimeField(blank=True, help_text='Timestamp when the appointment was completed.', null=True)),
                ('assigned_counselor', models.ForeignKey(blank=True, help_text='Office-assigned counselor.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_appointments', to=settings.AUTH_USER_MODEL)),
                ('preferred_counselor', models.ForeignKey(blank=True, help_text="Student's preferred counselor. Does not grant access.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='preferred_appointments', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, help_text='The staff/counselor who reviewed the appointment.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_appointments', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(help_text='The student who requested the appointment.', on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'appointment',
                'verbose_name_plural': 'appointments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AppointmentStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('from_status', models.CharField(blank=True, help_text='Previous status. Empty for initial creation.', max_length=50)),
                ('to_status', models.CharField(help_text='New status after transition.', max_length=50)),
                ('reason', models.TextField(blank=True, help_text='Optional reason for the transition.')),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='appointments.appointment')),
                ('changed_by', models.ForeignKey(help_text='The user who performed the transition.', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'appointment status history',
                'verbose_name_plural': 'appointment status histories',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AssignmentHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reason', models.TextField(blank=True, help_text='Reason for the assignment or reassignment.')),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignment_history', to='appointments.appointment')),
                ('assigned_by', models.ForeignKey(help_text='The user who performed the assignment.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('from_counselor', models.ForeignKey(blank=True, help_text='Previous assigned counselor. Null on initial assignment.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('to_counselor', models.ForeignKey(blank=True, help_text='New assigned counselor.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'assignment history',
                'verbose_name_plural': 'assignment histories',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AvailabilityRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('public_reference', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Opaque route reference; never display the database primary key.', unique=True)),
                ('day_of_week', models.PositiveSmallIntegerField(help_text='Day of week: 0=Monday through 6=Sunday (ISO weekday).')),
                ('start_time', models.TimeField(help_text='Start time for this availability window.')),
                ('end_time', models.TimeField(help_text='End time for this availability window.')),
                ('mode', models.CharField(choices=[('ONSITE', 'On-site'), ('ONLINE', 'Online'), ('BOTH', 'Both')], help_text='Availability mode: ONSITE, ONLINE, or BOTH.', max_length=10)),
                ('location', models.CharField(blank=True, help_text='Room or office description.', max_length=200)),
                ('slot_duration_minutes', models.PositiveIntegerField(default=60, help_text='Default slot duration in minutes.')),
                ('max_appointments_per_slot', models.PositiveIntegerField(default=1, help_text='Maximum appointments per slot.')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this rule is currently active.')),
                ('effective_from', models.DateField(help_text='Date when this rule becomes effective.')),
                ('effective_until', models.DateField(blank=True, help_text='Date when this rule ends. Null indicates indefinite.', null=True)),
                ('counselor', models.ForeignKey(help_text='The counselor whose availability is defined.', on_delete=django.db.models.deletion.CASCADE, related_name='availability_rules', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, help_text='The actor who recorded this rule.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_availability_rules', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'availability rule',
                'verbose_name_plural': 'availability rules',
                'ordering': ['counselor', 'day_of_week', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='OfficeClosure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField(help_text='Date of office closure.')),
                ('public_reference', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Opaque route reference; never display the database primary key.', unique=True)),
                ('start_time', models.TimeField(blank=True, help_text='Start time of closure. Null = entire day.', null=True)),
                ('end_time', models.TimeField(blank=True, help_text='End time of closure.', null=True)),
                ('reason', models.CharField(blank=True, help_text="E.g. 'Holiday', 'Campus event'.", max_length=200)),
                ('is_all_day', models.BooleanField(default=True, help_text='If true, the office is closed for the entire day.')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this closure currently affects slot calculation.')),
                ('created_by', models.ForeignKey(blank=True, help_text='The user who recorded this closure.', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'office closure',
                'verbose_name_plural': 'office closures',
                'ordering': ['date', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='ScheduleChangeEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('target_type', models.CharField(max_length=40)),
                ('target_object_id', models.CharField(max_length=40)),
                ('target_public_reference', models.UUIDField(blank=True, null=True)),
                ('action_type', models.CharField(max_length=40)),
                ('reason', models.CharField(max_length=200)),
                ('prior_state', models.JSONField(default=dict)),
                ('resulting_state', models.JSONField(default=dict)),
                ('pending_appointment_count', models.PositiveIntegerField(default=0)),
                ('scheduled_appointment_count', models.PositiveIntegerField(default=0)),
                ('affected_appointment_outcome', models.CharField(default='NONE', max_length=60)),
                ('request_key', models.CharField(max_length=64, unique=True)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schedule_change_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-pk'],
            },
        ),
        migrations.CreateModel(
            name='UnavailableBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('public_reference', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Opaque route reference; never display the database primary key.', unique=True)),
                ('date', models.DateField(help_text='Date of unavailability.')),
                ('start_time', models.TimeField(blank=True, help_text='Start time of unavailability. Null = entire day.', null=True)),
                ('end_time', models.TimeField(blank=True, help_text='End time of unavailability.', null=True)),
                ('reason', models.CharField(blank=True, help_text="E.g. 'Meeting', 'Leave'.", max_length=200)),
                ('is_all_day', models.BooleanField(default=False, help_text='If true, the counselor is unavailable for the entire day.')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this block currently affects slot calculation.')),
                ('counselor', models.ForeignKey(help_text='The counselor who is unavailable.', on_delete=django.db.models.deletion.CASCADE, related_name='unavailable_blocks', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, help_text='The actor who recorded this block.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_unavailable_blocks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'unavailable block',
                'verbose_name_plural': 'unavailable blocks',
                'ordering': ['counselor', 'date', 'start_time'],
            },
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['assigned_counselor', 'status'], name='appointment_assigne_41a695_idx'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['student', 'status'], name='appointment_student_632237_idx'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['status', 'confirmed_date'], name='appointment_status_b62db6_idx'),
        ),
        migrations.AddConstraint(
            model_name='appointment',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ('DRAFT', 'SUBMITTED', 'PENDING_REVIEW', 'APPROVED', 'SCHEDULED', 'LATE_CANCELLATION_REQUESTED', 'LATE_CANCELLATION_DECLINED'))), fields=('student',), name='uniq_active_appointment_per_student'),
        ),
        migrations.AddConstraint(
            model_name='availabilityrule',
            constraint=models.CheckConstraint(condition=models.Q(('slot_duration_minutes__gt', 0)), name='availability_rule_positive_duration'),
        ),
        migrations.AddConstraint(
            model_name='availabilityrule',
            constraint=models.CheckConstraint(condition=models.Q(('max_appointments_per_slot__gt', 0)), name='availability_rule_positive_capacity'),
        ),
        migrations.AddConstraint(
            model_name='officeclosure',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('end_time__isnull', True), ('is_all_day', True), ('start_time__isnull', True)), models.Q(('end_time__gt', models.F('start_time')), ('end_time__isnull', False), ('is_all_day', False), ('start_time__isnull', False)), _connector='OR'), name='office_closure_complete_interval'),
        ),
        migrations.AddIndex(
            model_name='schedulechangeevent',
            index=models.Index(fields=['target_type', 'target_object_id'], name='appointment_target__bdb604_idx'),
        ),
        migrations.AddIndex(
            model_name='schedulechangeevent',
            index=models.Index(fields=['action_type', 'created_at'], name='appointment_action__68e2a0_idx'),
        ),
        migrations.AddConstraint(
            model_name='unavailableblock',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('end_time__isnull', True), ('is_all_day', True), ('start_time__isnull', True)), models.Q(('end_time__gt', models.F('start_time')), ('end_time__isnull', False), ('is_all_day', False), ('start_time__isnull', False)), _connector='OR'), name='unavailable_block_complete_interval'),
        ),
    ]
