# Generated by Django 5.2.17 on 2026-09-07 14:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OnboardingCatalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.CharField(max_length=80, unique=True)),
                ('authority', models.CharField(choices=[('APPROVED', 'Institutionally approved'), ('DEMO_ONLY', 'Synthetic demo only')], default='DEMO_ONLY', max_length=20)),
                ('is_active', models.BooleanField(default=False)),
                ('source_reference', models.CharField(blank=True, max_length=255)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_onboarding_catalogs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'student onboarding catalog',
                'verbose_name_plural': 'student onboarding catalogs',
            },
        ),
        migrations.CreateModel(
            name='StudentImportBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_name', models.CharField(help_text='Name or description of the import source (e.g., OSSD Admission List).', max_length=255, verbose_name='source name')),
                ('academic_year', models.CharField(help_text='Target academic year for the import batch (e.g., 2026-2027).', max_length=50, verbose_name='academic year')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('VALIDATED', 'Validated'), ('IMPORTED', 'Imported'), ('PARTIALLY_IMPORTED', 'Partially Imported'), ('FAILED', 'Failed'), ('ARCHIVED', 'Archived'), ('NEEDS_REVIEW', 'Needs manual review'), ('APPROVED', 'Approved for execution'), ('EXECUTING', 'Executing'), ('EXECUTED', 'Executed'), ('SUPERSEDED', 'Superseded')], default='DRAFT', help_text='Operational workflow stage of the batch.', max_length=30, verbose_name='batch status')),
                ('validated_at', models.DateTimeField(blank=True, help_text='Timestamp when validation was run.', null=True, verbose_name='validated at')),
                ('executed_at', models.DateTimeField(blank=True, help_text='Timestamp when account provisioning was executed.', null=True, verbose_name='executed at')),
                ('template_version', models.CharField(blank=True, default='', max_length=40)),
                ('catalog_version', models.CharField(blank=True, default='', max_length=80)),
                ('content_hmac', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('validation_revision', models.PositiveIntegerField(default=0)),
                ('validation_digest', models.CharField(blank=True, default='', max_length=64)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('approved_digest', models.CharField(blank=True, default='', max_length=64)),
                ('approval_revoked_at', models.DateTimeField(blank=True, null=True)),
                ('approval_revocation_reason', models.CharField(blank=True, default='', max_length=80)),
                ('execution_idempotency_key', models.CharField(blank=True, default='', max_length=64)),
                ('execution_summary', models.JSONField(blank=True, default=dict)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_student_onboarding_batches', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created/uploaded this import batch.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_batches', to=settings.AUTH_USER_MODEL)),
                ('executed_by', models.ForeignKey(blank=True, help_text='User who executed account provisioning for this batch.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='executed_batches', to=settings.AUTH_USER_MODEL)),
                ('replacement_of', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replacements', to='imports.studentimportbatch')),
                ('validated_by', models.ForeignKey(blank=True, help_text='User who executed validation checks on this batch.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='validated_batches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'student import batch',
                'verbose_name_plural': 'student import batches',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StudentImportRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('row_number', models.PositiveIntegerField(help_text='Row index from the source CSV file.', verbose_name='row number')),
                ('control_number', models.CharField(blank=True, help_text='Temporary control number matching admissions tokens.', max_length=50, null=True, verbose_name='control number')),
                ('student_number', models.CharField(blank=True, help_text='Unique student ID number.', max_length=50, null=True, verbose_name='student number')),
                ('first_name', models.CharField(max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, help_text='Target institutional email address.', max_length=254, null=True, verbose_name='email address')),
                ('campus', models.CharField(blank=True, help_text='Target UCN campus.', max_length=100, verbose_name='campus')),
                ('college', models.CharField(blank=True, help_text='Target UCN college.', max_length=100, verbose_name='college')),
                ('department', models.CharField(blank=True, help_text='Target department.', max_length=100, verbose_name='department')),
                ('program', models.CharField(blank=True, help_text='Target academic program.', max_length=100, verbose_name='program')),
                ('program_code', models.CharField(blank=True, max_length=100, verbose_name='program code')),
                ('year_level', models.PositiveIntegerField(blank=True, help_text='Target year level.', null=True, verbose_name='year level')),
                ('lifecycle_status', models.CharField(choices=[('ACTIVE', 'Active'), ('GRADUATING', 'Graduating'), ('GRADUATED', 'Graduated'), ('ALUMNI', 'Alumni'), ('TRANSFERRED', 'Transferred'), ('DROPPED_INACTIVE', 'Dropped / Inactive'), ('SUSPENDED_RESTRICTED', 'Suspended / Restricted'), ('ARCHIVED', 'Archived')], default='ACTIVE', help_text='Enrollment status mapping.', max_length=30, verbose_name='lifecycle status')),
                ('validation_status', models.CharField(choices=[('PENDING', 'Pending'), ('VALID', 'Valid'), ('INVALID', 'Invalid'), ('IMPORTED', 'Imported'), ('SKIPPED', 'Skipped'), ('MANUAL_REVIEW', 'Manual review'), ('RECONCILED_EXISTING', 'Reconciled to existing profile'), ('EXCLUDED', 'Explicitly excluded'), ('PROVISIONED', 'Account provisioned'), ('SUPERSEDED', 'Superseded')], default='PENDING', help_text='Validation status of this individual row.', max_length=30, verbose_name='validation status')),
                ('error_message', models.TextField(blank=True, help_text='Description of any validation or execution errors (must not contain PII or control numbers).', null=True, verbose_name='error message')),
                ('error_code', models.CharField(blank=True, default='', max_length=60)),
                ('error_metadata', models.JSONField(blank=True, default=dict)),
                ('correction_revision', models.PositiveIntegerField(default=0)),
                ('correction_metadata', models.JSONField(blank=True, default=list)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('batch', models.ForeignKey(help_text='The import batch this row belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='rows', to='imports.studentimportbatch')),
                ('provisioned_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_onboarding_rows', to=settings.AUTH_USER_MODEL)),
                ('reconciled_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reconciled_onboarding_rows', to='profiles.studentprofile')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_student_onboarding_rows', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'student import row',
                'verbose_name_plural': 'student import rows',
                'ordering': ['batch', 'row_number'],
            },
        ),
        migrations.CreateModel(
            name='OnboardingProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('program_code', models.CharField(max_length=100)),
                ('campus', models.CharField(max_length=100)),
                ('college', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=100)),
                ('program', models.CharField(max_length=100)),
                ('max_year_level', models.PositiveIntegerField(default=4)),
                ('is_active', models.BooleanField(default=True)),
                ('catalog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programs', to='imports.onboardingcatalog')),
            ],
            options={
                'ordering': ['program_code'],
                'constraints': [models.UniqueConstraint(fields=('catalog', 'program_code'), name='uniq_onboarding_program_catalog_code')],
            },
        ),
        migrations.AddConstraint(
            model_name='studentimportbatch',
            constraint=models.UniqueConstraint(condition=models.Q(('template_version', 'student_onboarding-v1'), models.Q(('content_hmac', ''), _negated=True)), fields=('template_version', 'academic_year', 'content_hmac'), name='uniq_student_onboarding_content_hmac_per_academic_year'),
        ),
        migrations.AlterUniqueTogether(
            name='studentimportrow',
            unique_together={('batch', 'row_number')},
        ),
    ]
