# Generated by Django 5.2.17 on 2026-09-07 14:06

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stable_key', models.CharField(max_length=100, unique=True)),
                ('display_name', models.CharField(max_length=255)),
                ('channel', models.CharField(choices=[('in_app', 'In-App Only'), ('email', 'Email Only'), ('both', 'Both In-App and Email')], default='both', max_length=20)),
                ('subject_template', models.CharField(help_text='Subject template path or generic text.', max_length=255)),
                ('body_template', models.CharField(help_text='Body template path.', max_length=255)),
                ('html_body_template', models.CharField(blank=True, default='', help_text='Responsive HTML body template path.', max_length=255)),
                ('template_version', models.CharField(default='v1', max_length=30)),
                ('preference_policy', models.CharField(choices=[('user', 'User preference'), ('mandatory_security', 'Mandatory security')], default='user', max_length=30)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('retired', 'Retired')], default='active', max_length=20)),
                ('required_context_schema_json', models.JSONField(blank=True, default=dict, help_text='JSON schema validating context keys.')),
                ('sensitivity_classification', models.CharField(default='GENERAL', help_text='e.g. GENERAL, CONFIDENTIAL, RESTRICTED', max_length=50)),
                ('audit_category', models.CharField(default='NOTIFICATION', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('dedupe_key', models.CharField(blank=True, db_index=True, help_text='Deterministic non-sensitive key for one event/recipient notification.', max_length=64, null=True, unique=True)),
                ('recipient_role_snapshot', models.CharField(blank=True, help_text='Role of the recipient at time of notification.', max_length=50)),
                ('notification_type', models.CharField(help_text='Identifies the event type of the notification.', max_length=100)),
                ('title', models.CharField(max_length=255)),
                ('body_preview', models.CharField(help_text='Safe preview string. Must NOT contain sensitive details.', max_length=500)),
                ('related_object_type', models.CharField(blank=True, max_length=100, null=True)),
                ('related_object_id', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('unread', 'Unread'), ('read', 'Read'), ('archived', 'Archived')], db_index=True, default='unread', max_length=20)),
                ('priority', models.CharField(choices=[('normal', 'Normal'), ('high', 'High'), ('urgent', 'Urgent')], default='normal', max_length=20)),
                ('channel_intent', models.CharField(default='in_app', help_text='Intended delivery channels, e.g. in_app, email, both', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('metadata_json', models.JSONField(blank=True, default=dict, help_text='Safe, allowlisted metadata only.')),
                ('recipient_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EmailDelivery',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('delivery_key', models.CharField(help_text='Deterministic non-sensitive key preventing duplicate delivery enqueue.', max_length=64, unique=True)),
                ('recipient_email', models.CharField(help_text='Target recipient email address.', max_length=255)),
                ('template_key', models.CharField(max_length=100)),
                ('subject', models.CharField(help_text='Safe, generic subject line.', max_length=255)),
                ('context_json', models.JSONField(default=dict, help_text='Safe, privacyallowlisted context variables for rendering on send.')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('sent', 'Sent'), ('failed', 'Failed'), ('dead', 'Dead'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=20)),
                ('delivery_state', models.CharField(choices=[('queued', 'Queued'), ('sending', 'Sending'), ('sent', 'Sent (provider accepted)'), ('delayed', 'Delayed'), ('failed', 'Failed'), ('retry_exhausted', 'Retry exhausted'), ('bounced', 'Bounced'), ('cancelled', 'Cancelled')], db_index=True, default='queued', max_length=30)),
                ('attempts', models.IntegerField(default=0)),
                ('max_attempts', models.IntegerField(default=3)),
                ('next_retry_at', models.DateTimeField(db_index=True)),
                ('provider_message_id', models.CharField(blank=True, max_length=255, null=True)),
                ('last_error_code', models.CharField(blank=True, max_length=100, null=True)),
                ('last_error_safe_summary', models.TextField(blank=True, null=True)),
                ('related_object_type', models.CharField(blank=True, max_length=100, null=True)),
                ('related_object_id', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('locked_by', models.CharField(blank=True, max_length=255, null=True)),
                ('locked_at', models.DateTimeField(blank=True, null=True)),
                ('provider_feedback_hash', models.CharField(blank=True, db_index=True, max_length=64, null=True)),
                ('provider_status_updated_at', models.DateTimeField(blank=True, null=True)),
                ('recipient_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='email_deliveries', to=settings.AUTH_USER_MODEL)),
                ('notification', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='email_deliveries', to='notifications.notification')),
            ],
        ),
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(max_length=100)),
                ('in_app_enabled', models.BooleanField(default=True)),
                ('email_enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['recipient_user', 'status', 'created_at'], name='notificatio_recipie_08d144_idx'),
        ),
        migrations.AddIndex(
            model_name='emaildelivery',
            index=models.Index(fields=['status', 'next_retry_at'], name='notificatio_status_8da431_idx'),
        ),
        migrations.AddIndex(
            model_name='emaildelivery',
            index=models.Index(fields=['created_at'], name='notificatio_created_478847_idx'),
        ),
        migrations.AddConstraint(
            model_name='notificationpreference',
            constraint=models.UniqueConstraint(fields=('user', 'notification_type'), name='uniq_user_notification_type'),
        ),
    ]
